[album]
title = "THE IDOLM@STER SHINY COLORS ORIGINAL SOUNDTRACK"
artist = "稲垣敬也"
date = 2021-07-16
type = "absolute"
catalog = "ANCF-0015~7"
tags = ["THE IDOLM@STER Shiny Colors"]

[[discs]]
catalog = "ANCF-0015"

[[discs.tracks]]
title = "輝きはじめる私達の日常"

[[discs.tracks]]
title = "まったりいこうよ"

[[discs.tracks]]
title = "お気に入りの場所"

[[discs.tracks]]
title = "どうしたの？"

[[discs.tracks]]
title = "柔らかな夕暮れ"

[[discs.tracks]]
title = "ホッと一息安心感"

[[discs.tracks]]
title = "はやくはやく！"

[[discs.tracks]]
title = "昂るこの気持ちは…"

[[discs.tracks]]
title = "冗談だってば"

[[discs.tracks]]
title = "おもちゃ箱オーバースロー"

[[discs.tracks]]
title = "苦悩、挫折、それから—"

[[discs.tracks]]
title = "爽やかな朝"

[[discs.tracks]]
title = "ムスッとします…"

[[discs.tracks]]
title = "進め！283行進曲"

[[discs.tracks]]
title = "ラウンジポップな気分"

[[discs.tracks]]
title = "マイルドな日常"

[[discs.tracks]]
title = "悲しくても"

[[discs.tracks]]
title = "最後の朝"

[[discs.tracks]]
title = "スタンバイOK"

[[discs.tracks]]
title = "夢の先の、その景色"

[[discs.tracks]]
title = "プロデューサーさん"

[[discs]]
catalog = "ANCF-0016"

[[discs.tracks]]
title = "ワクワクでドキドキ"

[[discs.tracks]]
title = "始めよう！"

[[discs.tracks]]
title = "おめでとうございますー"

[[discs.tracks]]
title = "成長の記録"

[[discs.tracks]]
title = "元気にTV出演"

[[discs.tracks]]
title = "私、アイドルになれましたか？"

[[discs.tracks]]
title = "かっこよくTV出演"

[[discs.tracks]]
title = "夕暮れの達成感"

[[discs.tracks]]
title = "これからよろしくお願いします！！"

[[discs.tracks]]
title = "TOWN (SCmix)"

[[discs.tracks]]
title = "楽しみにしててよね"

[[discs.tracks]]
title = "フェスだよ！"

[[discs.tracks]]
title = "結果発表！"

[[discs.tracks]]
title = "まだまだこんなもんじゃないでしょ！"

[[discs.tracks]]
title = "34℃の空の下"

[[discs.tracks]]
title = "夕時ノスタルジック"

[[discs.tracks]]
title = "ハッピーハッピーハロウィーン！"

[[discs.tracks]]
title = "プロデューサー♪"

[[discs.tracks]]
title = "輝きはじめた私達の日常"

[[discs.tracks]]
title = "事務所で一人…じゃない！"

[[discs.tracks]]
title = "明けました283プロ"

[[discs]]
catalog = "ANCF-0017"

[[discs.tracks]]
title = "秘密の薔薇 -真実-"

[[discs.tracks]]
title = "君在ればこそ、君好ればこそ"

[[discs.tracks]]
title = "少しだけ高くしたヒールで"

[[discs.tracks]]
title = "レッスンはテンポよく"

[[discs.tracks]]
title = "おはようございます"

[[discs.tracks]]
title = "ドンドン進め！283行進曲"

[[discs.tracks]]
title = "ディメンション・ステージ"

[[discs.tracks]]
title = "力を合わせて、コラボフェス"

[[discs.tracks]]
title = "こころのいろは"

[[discs.tracks]]
title = "こころのいろは(復ち)"

[[discs.tracks]]
title = "雨音に寄り添う"

[[discs.tracks]]
title = "呼吸の温度"

[[discs.tracks]]
title = "きよしこの夜 (SCArrange)"

[[discs.tracks]]
title = "街灯りで照らされて"

[[discs.tracks]]
title = "88つの手触り"

[[discs.tracks]]
title = "小学5年生の1学期"

[[discs.tracks]]
title = "通過していく光の意味を"

[[discs.tracks]]
title = "輝いている私達の日常"

[[discs.tracks]]
title = "一歩ずつ、楽しくね"

[[discs.tracks]]
title = "149,600,000km"

[[discs.tracks]]
title = "プロデューサーさん！！"

[[discs.tracks]]
title = "エスプレッソと甘いクッキー"

[[discs.tracks]]
title = "インディムライト"
