[album]
album_id = "cd283973-657e-47df-be9f-5ea24ea8215f"
title = "冴えない彼女の育てかた Fine Featured Songs CD"
artist = "氷堂美智留（矢作紗友里）、澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）、加藤恵（安野希世乃）"
date = 2019-10-26
type = "normal"
catalog = "ANHC-34031"
tags = ["冴えない彼女の育てかた Fine"]

[[discs]]
catalog = "ANHC-34031"

[[discs.tracks]]
title = "icy tail YO!"
artist = "氷堂美智留（矢作紗友里）"

[[discs.tracks]]
title = "DREAM TEAM TRIANGLE"
artist = "澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）"

[[discs.tracks]]
title = "ULTIMATE♭"
artist = "加藤恵（安野希世乃）"

[[discs.tracks]]
title = "icy tail YO! (Instrumental)"
artist = "氷堂美智留（矢作紗友里）"
type = "instrumental"

[[discs.tracks]]
title = "DREAM TEAM TRIANGLE (Instrumental)"
artist = "澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）"
type = "instrumental"

[[discs.tracks]]
title = "ULTIMATE♭ (Instrumental)"
artist = "加藤恵（安野希世乃）"
type = "instrumental"
