[album]
title = "冴えない彼女の育てかた 第1巻 特典CD"
artist = "百石元"
date = 2015-03-04
type = "absolute"
catalog = "ANZX-11482"
tags = ["冴えない彼女の育てかた"]

[[discs]]
catalog = "ANZX-11482"

[[discs.tracks]]
title = "LOVE iLLUSiON"
artist = "霞ヶ丘詩羽（茅野愛衣）、加藤恵（安野希世乃）、澤村・スペンサー・英梨々（大西沙織）"
type = "normal"

[[discs.tracks]]
title = "LOVE iLLUSiON (Off Vocal Ver.)"
artist = "霞ヶ丘詩羽（茅野愛衣）、加藤恵（安野希世乃）、澤村・スペンサー・英梨々（大西沙織）"
type = "instrumental"

[[discs.tracks]]
title = "メインテーマ"

[[discs.tracks]]
title = "出会い (Piano Solo Ver.)"

[[discs.tracks]]
title = "わが道を行く"

[[discs.tracks]]
title = "まったくなんだかなあ"
artist = "やまぞう"

[[discs.tracks]]
title = "マシンガントーク"

[[discs.tracks]]
title = "コミカルサスペンス"

[[discs.tracks]]
title = "失意 その3"

[[discs.tracks]]
title = "充実の一日"
