[album]
title = "冴えない彼女の育てかた♭ 第3巻 特典CD"
artist = "百石元"
date = 2017-09-27
type = "absolute"
catalog = "ANZX-13386"
tags = ["冴えない彼女の育てかた♭"]

[[discs]]
catalog = "ANZX-13386"

[[discs.tracks]]
title = "届かない恋"
artist = "霞ヶ丘詩羽（茅野愛衣）"
type = "normal"

[[discs.tracks]]
title = "じゃれ合い"

[[discs.tracks]]
title = "オクラホマミキサー"

[[discs.tracks]]
title = "不穏"

[[discs.tracks]]
title = "薄氷のような決意"
