[album]
title = "冴えない彼女の育てかた♭ 第1巻 特典CD"
artist = "百石元"
date = 2017-07-26
type = "absolute"
catalog = "ANZX-13382"

[[discs]]
catalog = "ANZX-13382"

[[discs.tracks]]
title = "檄！帝国華撃団"
artist = "加藤恵（安野希世乃）、澤村・スペンサー・英梨々（大西沙織）、霞ヶ丘詩羽（茅野愛衣）、氷堂美智留（矢作紗友里）、波島出海（赤崎千夏）"
type = "normal"

[[discs.tracks]]
title = "変わらない日常"

[[discs.tracks]]
title = "いじられモード"

[[discs.tracks]]
title = "Daydreamer (Michiru Guitar Solo ver.)"

[[discs.tracks]]
title = "因縁"
