[album]
album_id = "6c7c4689-0405-4677-bd70-8568741731e5"
title = "冴えない彼女の育てかた♭ 第5巻 特典CD"
artist = "百石元"
date = 2017-11-22
type = "absolute"
catalog = "ANZX-13390"
tags = ["冴えない彼女の育てかた♭"]

[[discs]]
catalog = "ANZX-13390"

[[discs.tracks]]
title = "true my heart"
artist = "波島出海（赤﨑千夏）"
type = "normal"

[[discs.tracks]]
title = "雪どけ"

[[discs.tracks]]
title = "恵のぬくもり"

[[discs.tracks]]
title = "疑心暗鬼"

[[discs.tracks]]
title = "紅坂朱音"
