[album]
title = "冴えない彼女の育てかた 第3巻 特典CD"
artist = "百石元"
date = 2015-05-13
type = "absolute"
catalog = "ANZX-11486"

[[discs]]
catalog = "ANZX-11486"

[[discs.tracks]]
title = "Leaf ticket"
artist = "加藤恵（安野希世乃）"
type = "normal"

[[discs.tracks]]
title = "さわやかな朝 (Piano Solo Ver.)"

[[discs.tracks]]
title = "モノ申す！"

[[discs.tracks]]
title = "緊張感"

[[discs.tracks]]
title = "出会い"

[[discs.tracks]]
title = "楽しいねぇ♪"

[[discs.tracks]]
title = "小競り合い"

[[discs.tracks]]
title = "本気モード"

[[discs.tracks]]
title = "いいムード"
