[album]
title = "冴えない彼女の育てかた♭ 第2巻 特典CD"
artist = "百石元"
date = 2017-08-23
type = "absolute"
catalog = "ANZX-13384"

[[discs]]
catalog = "ANZX-13384"

[[discs.tracks]]
title = "Little Busters!"
artist = "氷堂美智留（矢作紗友里）"
type = "normal"

[[discs.tracks]]
title = "呆れ"

[[discs.tracks]]
title = "巡璃ルート"

[[discs.tracks]]
title = "対立"

[[discs.tracks]]
title = "大忙し"

[[discs.tracks]]
title = "否定"
