[album]
album_id = "02997ee9-5c4a-4ff5-a7b3-348a8cd2a7f9"
title = "冴えない彼女の育てかた♭ 第4巻 特典CD"
artist = "百石元"
date = 2017-10-25
type = "absolute"
catalog = "ANZX-13388"
tags = ["冴えない彼女の育てかた♭"]

[[discs]]
catalog = "ANZX-13388"

[[discs.tracks]]
title = "allegretto ～そらときみ～"
artist = "澤村・スペンサー・英梨々（大西沙織）"
type = "normal"

[[discs.tracks]]
title = "問題と現状分析"

[[discs.tracks]]
title = "気がかり"

[[discs.tracks]]
title = "一件落着"

[[discs.tracks]]
title = "焦りといら立ち"

[[discs.tracks]]
title = "祭りのあと"
