[album]
album_id = "5665dad6-dadc-4e13-95c2-fdd4709d2137"
title = "冴えない彼女の育てかた 第4巻 特典CD"
artist = "百石元"
date = 2015-06-03
type = "absolute"
catalog = "ANZX-11488"
tags = ["冴えない彼女の育てかた"]

[[discs]]
catalog = "ANZX-11488"

[[discs.tracks]]
title = "(Vocal) you"
artist = "霞ヶ丘詩羽（茅野愛衣）"
type = "normal"

[[discs.tracks]]
title = "孤高の人"

[[discs.tracks]]
title = "挑発"

[[discs.tracks]]
title = "ご機嫌ななめ"

[[discs.tracks]]
title = "悲哀"

[[discs.tracks]]
title = "情熱的自説展開"
artist = "やまぞう"

[[discs.tracks]]
title = "不本意"

[[discs.tracks]]
title = "あふれるアイディア"

[[discs.tracks]]
title = "トランスモード"

[[discs.tracks]]
title = "懐かしい日"
