[album]
title = "冴えない彼女の育てかた 第6巻 特典CD"
artist = "百石元"
date = 2015-08-05
type = "absolute"
catalog = "ANZX-11492"
tags = ["冴えない彼女の育てかた"]

[[discs]]
catalog = "ANZX-11492"

[[discs.tracks]]
title = "グリーングリーン"
artist = "氷堂美智留（矢作紗友里）"
type = "normal"

[[discs.tracks]]
title = "ひたむきな想い"

[[discs.tracks]]
title = "時間がない"

[[discs.tracks]]
title = "切なさ"

[[discs.tracks]]
title = "恋心"

[[discs.tracks]]
title = "元気いっぱい"

[[discs.tracks]]
title = "気まずい"

[[discs.tracks]]
title = "タジタジ"

[[discs.tracks]]
title = "憔悴"

[[discs.tracks]]
title = "サブテーマ (Bossa Version)"
