[album]
title = "冴えない彼女の育てかた Fine ORIGINAL SOUNDTRACK"
artist = "百石元"
date = 2020-09-23
type = "absolute"
catalog = "ANZX-13653"

[[discs]]
catalog = "ANZX-13653"

[[discs.tracks]]
title = "必要な時間"

[[discs.tracks]]
title = "緊張"

[[discs.tracks]]
title = "隠し事"

[[discs.tracks]]
title = "引き留め"

[[discs.tracks]]
title = "やっぱり"

[[discs.tracks]]
title = "ここにいる意味"

[[discs.tracks]]
title = "2人の覚悟"

[[discs.tracks]]
title = "ごめんね"

[[discs.tracks]]
title = "おしまい"
