[album]
title = "needLe／ステラ"
artist = "Leo/need（星乃一歌（野口瑠璃子）、天馬咲希（礒部花凛）、望月穂波（上田麗奈）、日野森志歩（中島由貴））、初音ミク"
date = 2021-06-09
type = "normal"
catalog = "BRMM-10402"
tags = ["Leo/need"]

[[discs]]
catalog = "BRMM-10402"

[[discs.tracks]]
title = "needLe"

[[discs.tracks]]
title = "ステラ"

[[discs.tracks]]
title = "needLe（instrumental）"
type = "instrumental"

[[discs.tracks]]
title = "ステラ（instrumental）"
type = "instrumental"
