[album]
album_id = "a07388b6-690b-413e-8cec-19492fac0716"
title = "セカイはまだ始まってすらいない／potatoになっていく"
artist = "ワンダーランズ×ショウタイム（天馬司（廣瀬大介）、鳳えむ（木野日菜）、草薙寧々（Machico）、神代類（土岐隼一））、初音ミク"
date = 2021-07-21
type = "normal"
catalog = "BRMM-10405"
tags = ["ワンダーランズ×ショウタイム"]

[[discs]]
catalog = "BRMM-10405"

[[discs.tracks]]
title = "セカイはまだ始まってすらいない"

[[discs.tracks]]
title = "potatoになっていく"

[[discs.tracks]]
title = "セカイはまだ始まってすらいない (instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "potatoになっていく (instrumental)"
type = "instrumental"
