[album]
album_id = "ebebe18d-96be-4bad-a020-3cb6ec06fcaf"
title = "アイドル新鋭隊／モア！ジャンプ！モア！"
artist = "MORE MORE JUMP！（花里みのり（小倉唯）、桐谷遥（吉岡茉祐）、桃井愛莉（降幡愛）、日野森雫（本泉莉奈））、初音ミク"
date = 2021-06-23
type = "normal"
catalog = "BRMM-10403"
tags = ["MORE MORE JUMP！"]

[[discs]]
catalog = "BRMM-10403"

[[discs.tracks]]
title = "アイドル新鋭隊"

[[discs.tracks]]
title = "モア！ジャンプ！モア！"

[[discs.tracks]]
title = "アイドル新鋭隊 (instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "モア！ジャンプ！モア！(instrumental)"
type = "instrumental"
