[album]
album_id = "c3233c94-304f-4333-80db-64933e577666"
title = "THE IDOLM@STER CINDERELLA MASTER 062 久川颯"
artist = "久川颯（長江里加）"
date = 2022-04-20
type = "normal"
catalog = "COCC-18009"
tags = ["THE IDOLM@STER CINDERELLA MASTER (ソロCD)"]

[[discs]]
catalog = "COCC-18009"

[[discs.tracks]]
title = "Packing Her Favorite"

[[discs.tracks]]
title = "ドラマ「もーっと目指せ！シンデレラNo.1! －久川颯編－」"
artist = "久川颯（長江里加）、ナターリア（生田輝）"
type = "drama"

[[discs.tracks]]
title = "Packing Her Favorite オリジナル・カラオケ"
type = "instrumental"

[[discs.tracks]]
title = "ボーナス・トラック"
type = "vocal"
