[album]
album_id = "3cea9f06-4d8c-457a-8a1c-294e028b67a2"
title = "THE IDOLM@STER CINDERELLA MASTER 063 ナターリア"
artist = "ナターリア（生田輝）"
date = 2022-04-20
type = "normal"
catalog = "COCC-18010"
tags = ["THE IDOLM@STER CINDERELLA MASTER (ソロCD)"]

[[discs]]
catalog = "COCC-18010"

[[discs.tracks]]
title = "ソウソウ"

[[discs.tracks]]
title = "ドラマ「もーっと目指せ！シンデレラNo.1! －ナターリア編－」"
artist = "ナターリア（生田輝）、辻野あかり（梅澤めぐ）"
type = "drama"

[[discs.tracks]]
title = "ソウソウ オリジナル・カラオケ"
type = "instrumental"

[[discs.tracks]]
title = "ボーナス・トラック"
type = "vocal"
