[album]
album_id = "7a08cef6-4cde-41b3-b8ef-c12a32c5caa8"
title = "CHAOS;CHILD 限定版ドラマCD「間に合わぬ愚者の微睡-Fools」"
artist = "宮代拓留（松岡禎丞）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、有村雛絵（三森すずこ）、久野里澪（種田梨沙）、香月華（仲谷明香）、伊藤真二（藤原祐規）"
date = 2015-06-25
type = "drama"
catalog = "FPBD-0318"
tags = ["CHAOS;CHILD"]

[[discs]]
catalog = "FPBD-0318"

[[discs.tracks]]
title = "間に合わぬ愚者の微睡-Fools #01"

[[discs.tracks]]
title = "間に合わぬ愚者の微睡-Fools #02"

[[discs.tracks]]
title = "間に合わぬ愚者の微睡-Fools #03"

[[discs.tracks]]
title = "間に合わぬ愚者の微睡-Fools #04"

[[discs.tracks]]
title = "間に合わぬ愚者の微睡-Fools #05"

[[discs.tracks]]
title = "間に合わぬ愚者の微睡-Fools #06"
