[album]
album_id = "b3c489e0-c330-4729-a801-08899db29720"
title = "Real Boot Modulation -CHAOS;CHILD OST-"
artist = "阿保剛"
date = 2016-03-23
type = "absolute"
catalog = "FVCG-1369"
tags = ["CHAOS;CHILD"]

[[discs]]
catalog = "FVCG-1369-01"

[[discs.tracks]]
title = "WORLD -C;C MAIN THEME-"

[[discs.tracks]]
title = "THE THIRD MELT"

[[discs.tracks]]
title = "VIEWPOINT"

[[discs.tracks]]
title = "COUNT DOWN"

[[discs.tracks]]
title = "PEAK LEVEL"

[[discs.tracks]]
title = "NEUTRALS"

[[discs.tracks]]
title = "REVIVED SHIBUYA"

[[discs.tracks]]
title = "CAPACITY"

[[discs.tracks]]
title = "FAIRY’S DANCE"

[[discs.tracks]]
title = "INSPECTION"

[[discs.tracks]]
title = "MAPPING MODE"

[[discs.tracks]]
title = "AN INTERFERER IN WHITE"

[[discs.tracks]]
title = "GIRLISH"

[[discs.tracks]]
title = "GAG"

[[discs.tracks]]
title = "THEN"

[[discs.tracks]]
title = "SUMO SEAL"

[[discs.tracks]]
title = "AH TOKYO GENERAL HOSPITAL"

[[discs.tracks]]
title = "RORSCHACH TEST"

[[discs.tracks]]
title = "NETWORKER"

[[discs.tracks]]
title = "HER WORRIES"

[[discs.tracks]]
title = "ONLINE NOW"

[[discs.tracks]]
title = "THE AIR OF TERROR"

[[discs.tracks]]
title = "SHADY AMBIENCE"

[[discs.tracks]]
title = "WHAT WAS LOST"

[[discs.tracks]]
title = "Spark Wars"

[[discs.tracks]]
title = "MORE GRIEF"

[[discs.tracks]]
title = "非実在青少年"
artist = "いとうかなこ"
type = "normal"

[[discs.tracks]]
title = "シンギュラリティ"
artist = "いとうかなこ"
type = "normal"

[[discs]]
catalog = "FVCG-1369-02"

[[discs.tracks]]
title = "COUNT DOWN -another-"

[[discs.tracks]]
title = "NEUTRALS -another-"

[[discs.tracks]]
title = "REVIVED SHIBUYA -another-"

[[discs.tracks]]
title = "FAIRY’S DANCE -another-"

[[discs.tracks]]
title = "INSPECTION -another-"

[[discs.tracks]]
title = "MAPPING MODE -another-"

[[discs.tracks]]
title = "GIRLISH -another-"

[[discs.tracks]]
title = "SUMO SEAL -another-"

[[discs.tracks]]
title = "AH TOKYO GENERAL HOSPITAL -another-"

[[discs.tracks]]
title = "RORSCHACH TEST -another-"

[[discs.tracks]]
title = "THE AIR OF TERROR -another-"

[[discs.tracks]]
title = "FLASHBACK"

[[discs.tracks]]
title = "DUSK"

[[discs.tracks]]
title = "FAR DAYS"

[[discs.tracks]]
title = "GIRLISH -PIANO-"

[[discs.tracks]]
title = "DID YOU ENJOY?"

[[discs.tracks]]
title = "VISIBLE ESSENCE"

[[discs.tracks]]
title = "HE IS …"

[[discs.tracks]]
title = "BREAK FORTH"

[[discs.tracks]]
title = "DI-SWORD OF SADNESS"

[[discs.tracks]]
title = "LAST LINE -SHIBUYA-"

[[discs.tracks]]
title = "RESET"

[[discs.tracks]]
title = "VIEWPOINT -jingle-"

[[discs.tracks]]
title = "INSPECTION -jingle-"

[[discs.tracks]]
title = "THEN -jingle-"

[[discs.tracks]]
title = "THE AIR OF TERROR -jingle-"

[[discs.tracks]]
title = "SHADY AMBIENCE -jingle-"

[[discs.tracks]]
title = "SILENT WORLD"

[[discs.tracks]]
title = "RE:START"

[[discs.tracks]]
title = "月蝕のヴァニタス"
artist = "ファンタズム（榊原ゆい）"
type = "normal"

[[discs.tracks]]
title = "silent wind bell"
artist = "いとうかなこ"
type = "normal"
