[album]
title = "Foooo are you?"
artist = "狩手結良（大西沙織）"
date = 2021-01-29
type = "normal"
catalog = "GNXA-1592"

[[discs]]
catalog = "GNXA-1592"

[[discs.tracks]]
title = "Foooo are you?"

[[discs.tracks]]
title = "Foooo are you? (Instrumental)"
type = "instrumental"
