[album]
title = "CHAOS;CHILD AUDIO DRAMA & RADIO DIGEST VOL.7"
artist = "Various Artists"
date = 2017-09-29
type = "radio"
catalog = "KAXA-7497CD"
tags = ["CHAOS;CHILD SILENT SKY"]

[[discs]]
catalog = "KAXA-7497CD"

[[discs.tracks]]
title = "オーディオドラマ「夢」(尾上世莉架編) #1"
artist = "宮代拓留（松岡禎丞）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、有村雛絵（三森すずこ）、香月華（仲谷明香）、山添うき（水瀬いのり）、伊藤真二（藤原祐規）、橘結衣（原由実）"
type = "drama"

[[discs.tracks]]
title = "オーディオドラマ「夢」(尾上世莉架編) #2"
artist = "宮代拓留（松岡禎丞）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、有村雛絵（三森すずこ）、香月華（仲谷明香）、山添うき（水瀬いのり）、伊藤真二（藤原祐規）、橘結衣（原由実）"
type = "drama"

[[discs.tracks]]
title = "オーディオドラマ「夢」(尾上世莉架編) #3"
artist = "宮代拓留（松岡禎丞）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、有村雛絵（三森すずこ）、香月華（仲谷明香）、山添うき（水瀬いのり）、伊藤真二（藤原祐規）、橘結衣（原由実）"
type = "drama"

[[discs.tracks]]
title = "オーディオドラマ「夢」(尾上世莉架編) #4"
artist = "宮代拓留（松岡禎丞）、尾上世莉架（上坂すみれ）、来栖乃々（ブリドカットセーラ恵美）、有村雛絵（三森すずこ）、香月華（仲谷明香）、山添うき（水瀬いのり）、伊藤真二（藤原祐規）、橘結衣（原由実）"
type = "drama"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第15回・第16回ダイジェスト> #1"
artist = "ブリドカットセーラ恵美、水瀬いのり"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第15回・第16回ダイジェスト> #2"
artist = "ブリドカットセーラ恵美、水瀬いのり"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第15回・第16回ダイジェスト> #3"
artist = "ブリドカットセーラ恵美、水瀬いのり"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第15回・第16回ダイジェスト> #4"
artist = "ブリドカットセーラ恵美、水瀬いのり"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第15回・第16回ダイジェスト> #5"
artist = "ブリドカットセーラ恵美、水瀬いのり"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第15回・第16回ダイジェスト> #6"
artist = "ブリドカットセーラ恵美、水瀬いのり"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第15回・第16回ダイジェスト> #7"
artist = "ブリドカットセーラ恵美、水瀬いのり"

[[discs.tracks]]
title = "「CHAOS;CHILD Mou☆Sou RADIO! 碧朋学園新聞部 校内放送」<第15回・第16回ダイジェスト> #8"
artist = "ブリドカットセーラ恵美、水瀬いのり"
