[album]
album_id = "11561ac0-439f-4772-a066-c565a354a615"
title = "ライザのアトリエ ～常闇の女王と秘密の隠れ家～ オリジナルサウンドトラック"
artist = "Various Artists"
date = 2019-09-25
type = "absolute"
catalog = "KECH-8081~2"
tags = ["ライザのアトリエ"]

[[discs]]
catalog = "KECH-8081"

[[discs.tracks]]
title = "虹色の夏"
artist = "神田沙也加"
type = "normal"

[[discs.tracks]]
title = "ひと夏の大冒険"
artist = "三武亜紗美"

[[discs.tracks]]
title = "ソラミミ"
artist = "柳川和樹"

[[discs.tracks]]
title = "銀の音さやか"
artist = "柳川和樹"

[[discs.tracks]]
title = "願いと大剣"
artist = "柳川和樹"

[[discs.tracks]]
title = "透明な栞"
artist = "柳川和樹"

[[discs.tracks]]
title = "また手をつないだら"
artist = "柳川和樹"

[[discs.tracks]]
title = "新芽探して"
artist = "柳川和樹"

[[discs.tracks]]
title = "次のページは何だろう"
artist = "柳川和樹"

[[discs.tracks]]
title = "棚を挟んで、はにかんで"
artist = "柳川和樹"

[[discs.tracks]]
title = "荷物を一度置いて"
artist = "柳川和樹"

[[discs.tracks]]
title = "青草香る空の下"
artist = "柳川和樹"

[[discs.tracks]]
title = "水彩色に跳ねる日々"
artist = "柳川和樹"

[[discs.tracks]]
title = "二番星が灯る前に"
artist = "柳川和樹"

[[discs.tracks]]
title = "日向水"
artist = "柳川和樹"

[[discs.tracks]]
title = "コギト"
artist = "柳川和樹"

[[discs.tracks]]
title = "夕立"
artist = "柳川和樹"

[[discs.tracks]]
title = "へじへじものへ"
artist = "柳川和樹"

[[discs.tracks]]
title = "なんてことない毎日"
artist = "三武亜紗美"

[[discs.tracks]]
title = "秘密の隠れ家"
artist = "三武亜紗美"

[[discs.tracks]]
title = "故郷の島"
artist = "水上浩介"

[[discs.tracks]]
title = "静寂の島"
artist = "水上浩介"

[[discs.tracks]]
title = "果てなく続く道"
artist = "中村新一郎"

[[discs.tracks]]
title = "星空のもと"
artist = "中村新一郎"

[[discs.tracks]]
title = "小妖精の森"
artist = "中村新一郎"

[[discs.tracks]]
title = "森の密会"
artist = "中村新一郎"

[[discs.tracks]]
title = "Grotta Azzurra"
artist = "水上浩介"

[[discs.tracks]]
title = "Grotta dello Zaffiro"
artist = "水上浩介"

[[discs.tracks]]
title = "流星の古城にて"
artist = "中村新一郎"

[[discs.tracks]]
title = "朽ちた砦"
artist = "中村新一郎"

[[discs.tracks]]
title = "啓蟄、嬰の足"
artist = "アサノハヤト"

[[discs.tracks]]
title = "白南風"
artist = "アサノハヤト"

[[discs.tracks]]
title = "凱歌のファンファーレ"
artist = "中村新一郎"

[[discs]]
catalog = "KECH-8082"

[[discs.tracks]]
title = "この手でも掴める何か"
artist = "柳川和樹"

[[discs.tracks]]
title = "風静か"
artist = "柳川和樹"

[[discs.tracks]]
title = "紅葉と鳥のうた"
artist = "三武亜紗美"

[[discs.tracks]]
title = "夜風と星のうた"
artist = "三武亜紗美"

[[discs.tracks]]
title = "Ash Climbing"
artist = "水上浩介"

[[discs.tracks]]
title = "Emerald Climbing"
artist = "水上浩介"

[[discs.tracks]]
title = "かつての夢の集まる場"
artist = "三武亜紗美"

[[discs.tracks]]
title = "夢見る廃墟"
artist = "三武亜紗美"

[[discs.tracks]]
title = "古の谷"
artist = "水上浩介"

[[discs.tracks]]
title = "ダイヤモンドの谷"
artist = "水上浩介"

[[discs.tracks]]
title = "巨木と結晶の楼"
artist = "中村新一郎"

[[discs.tracks]]
title = "聖なる楼閣"
artist = "中村新一郎"

[[discs.tracks]]
title = "GEO FRONTIER"
artist = "水上浩介"

[[discs.tracks]]
title = "女王の城へ"
artist = "三武亜紗美"

[[discs.tracks]]
title = "小瓶の中の楽園"
artist = "中村新一郎"

[[discs.tracks]]
title = "Rubis de Lave"
artist = "水上浩介"

[[discs.tracks]]
title = "採取？バカンス？"
artist = "三武亜紗美"

[[discs.tracks]]
title = "星座をかぞえて"
artist = "三武亜紗美"

[[discs.tracks]]
title = 'Etude "Andante"'
artist = "柳川和樹"

[[discs.tracks]]
title = "君と出逢えた奇跡～ゲームver インスト～"
artist = "中村新一郎"

[[discs.tracks]]
title = "涙色の夏"
artist = "水上浩介"

[[discs.tracks]]
title = "動き出す夏"
artist = "水上浩介"

[[discs.tracks]]
title = "穀雨、麦の風"
artist = "アサノハヤト"

[[discs.tracks]]
title = "Won't forget, can't regret."
artist = "アサノハヤト"

[[discs.tracks]]
title = "Look inside yourself. You are more than what you have become."
artist = "アサノハヤト"

[[discs.tracks]]
title = "MEDIOCRIS"
artist = "中村新一郎"

[[discs.tracks]]
title = "Crocus"
artist = "弐八さん"

[[discs.tracks]]
title = "君と出逢えた奇跡"
artist = "照井春佳、三上枝織"
type = "normal"
