[album]
album_id = "788122f6-086b-4472-aafd-66de70861f9d"
title = "ライザのアトリエ2 ～失われた伝承と秘密の妖精～ オリジナルサウンドトラック"
artist = "Various Artists"
date = 2020-12-02
type = "absolute"
catalog = "KECH-8083~4"
tags = ["ライザのアトリエ2"]

[[discs]]
catalog = "KECH-8083"

[[discs.tracks]]
title = "Somewhen, Somewhere..."
artist = "クラムボン"

[[discs.tracks]]
title = "新しい大冒険～from ひと夏の大冒険～"
artist = "松村佑樹"

[[discs.tracks]]
title = "未知への冒険～fromソラミミ～"
artist = "裏谷玲央"

[[discs.tracks]]
title = "光と風の音色～from銀の音さやか～"
artist = "裏谷玲央"

[[discs.tracks]]
title = "その腕の先に～from願いと大剣～"
artist = "裏谷玲央"

[[discs.tracks]]
title = "知への探求心～from透明な栞～"
artist = "裏谷玲央"

[[discs.tracks]]
title = "あの夏の思い出"
artist = "松村佑樹"

[[discs.tracks]]
title = "よし、じゃあ始めるよ"
artist = "松村佑樹"

[[discs.tracks]]
title = "なるほど、なるほどなー"
artist = "松村佑樹"

[[discs.tracks]]
title = "王都の賑わい"
artist = "松村佑樹"

[[discs.tracks]]
title = "ひとやすみ"
artist = "松村佑樹"

[[discs.tracks]]
title = "今日も晴れです!"
artist = "松村佑樹"

[[discs.tracks]]
title = "少し高い空の下"
artist = "柳川和樹"

[[discs.tracks]]
title = "のんびりしてもいいよね?"
artist = "松村佑樹"

[[discs.tracks]]
title = "淡い夕日"
artist = "裏谷玲央"

[[discs.tracks]]
title = "迫りくる足音"
artist = "裏谷玲央"

[[discs.tracks]]
title = "夢境"
artist = "柳川和樹"

[[discs.tracks]]
title = "泥濘"
artist = "柳川和樹"

[[discs.tracks]]
title = "その目の先に映るのは"
artist = "松村佑樹"

[[discs.tracks]]
title = "危機と焦り"
artist = "裏谷玲央"

[[discs.tracks]]
title = "小石がなくても躓くの"
artist = "柳川和樹"

[[discs.tracks]]
title = "新たなる冒険の拠点"
artist = "裏谷玲央"

[[discs.tracks]]
title = "石畳にはずむステップ"
artist = "三武亜紗美"

[[discs.tracks]]
title = "街灯りは揺らめいて"
artist = "三武亜紗美"

[[discs.tracks]]
title = "海風を背に受けて"
artist = "松村佑樹"

[[discs.tracks]]
title = "星空の大地"
artist = "松村佑樹"

[[discs.tracks]]
title = "木々の距離ほど近く"
artist = "柳川和樹"

[[discs.tracks]]
title = "星々の距離ほど遠く"
artist = "柳川和樹"

[[discs.tracks]]
title = "Deep Forest Daylight"
artist = "裏谷玲央"

[[discs.tracks]]
title = "Deep Forest Night"
artist = "裏谷玲央"

[[discs.tracks]]
title = "芒種、鼠黐の薫風"
artist = "アサノハヤト"

[[discs.tracks]]
title = "It's all uphill from here"
artist = "アサノハヤト"

[[discs.tracks]]
title = "勝利の記憶"
artist = "松村佑樹"

[[discs]]
catalog = "KECH-8084"

[[discs.tracks]]
title = "自由への夢"
artist = "裏谷玲央"

[[discs.tracks]]
title = "流離のトレジャーハンター"
artist = "裏谷玲央"

[[discs.tracks]]
title = "緑と自然の恵みと"
artist = "裏谷玲央"

[[discs.tracks]]
title = "月に叢雲～fromソラミミ～"
artist = "裏谷玲央"

[[discs.tracks]]
title = "ちいさな変化"
artist = "松村佑樹"

[[discs.tracks]]
title = "新たな一手"
artist = "松村佑樹"

[[discs.tracks]]
title = "渓谷を渡る鳥"
artist = "松村佑樹"

[[discs.tracks]]
title = "渓谷に眠る月"
artist = "松村佑樹"

[[discs.tracks]]
title = "忘れられた場所"
artist = "松村佑樹"

[[discs.tracks]]
title = "渇いた巡りの地"
artist = "柳川和樹"

[[discs.tracks]]
title = "渇いた眠りの地"
artist = "柳川和樹"

[[discs.tracks]]
title = "いにしえの鐘の音"
artist = "三武亜紗美"

[[discs.tracks]]
title = "火の宿るところ"
artist = "柳川和樹"

[[discs.tracks]]
title = "水面に映る星の都"
artist = "三武亜紗美"

[[discs.tracks]]
title = "深森に呑まれて"
artist = "柳川和樹"

[[discs.tracks]]
title = "谷底の古道"
artist = "柳川和樹"

[[discs.tracks]]
title = "追憶の羅針盤"
artist = "三武亜紗美"

[[discs.tracks]]
title = "終の歴史を超えて"
artist = "三武亜紗美"

[[discs.tracks]]
title = "また、冒険できるね ～from ひと夏の大冒険～"
artist = "柳川和樹"

[[discs.tracks]]
title = "Hands - climax"
artist = "水上浩介"

[[discs.tracks]]
title = 'Etude "Adagio"'
artist = "柳川和樹"

[[discs.tracks]]
title = "ハンドサイン"
artist = "柳川和樹"

[[discs.tracks]]
title = "白露、荻の上風"
artist = "アサノハヤト"

[[discs.tracks]]
title = "ヤロカミズ"
artist = "アサノハヤト"

[[discs.tracks]]
title = "wish"
artist = "アサノハヤト"

[[discs.tracks]]
title = "脅威との対峙"
artist = "裏谷玲央"

[[discs.tracks]]
title = "Hands"
artist = "琴音"
