[album]
title = "harmony ribbon"
artist = "水瀬いのり"
date = 2016-04-13
type = "normal"
catalog = "KICM-1662"

[[discs]]
catalog = "KICM-1662"

[[discs.tracks]]
title = "harmony ribbon"

[[discs.tracks]]
title = "Dreaming Girls"

[[discs.tracks]]
title = "Ring of Smile"
