[album]
album_id = "def4bac0-4b06-47ff-916b-32b223c9f685"
title = "ハピネス"
artist = "岡咲美保"
date = 2021-09-15
type = "normal"
catalog = "KIZM-695"
tags = ["岡咲美保"]

[[discs]]
catalog = "KIZM-695"

[[discs.tracks]]
title = "ハピネス"

[[discs.tracks]]
title = "Popping Moments"

[[discs.tracks]]
title = "MY SPIRAL"

[[discs.tracks]]
title = "ハピネス (off vocal version)"
type = "instrumental"

[[discs.tracks]]
title = "Popping Moments (off vocal version)"
type = "instrumental"

[[discs.tracks]]
title = "MY SPIRAL (off vocal version)"
type = "instrumental"

[[discs.tracks]]
title = "スペシャルボイスメッセージ"
type = "vocal"
