[album]
title = "ペタルズ"
artist = "岡咲美保"
date = 2021-11-03
type = "normal"
catalog = "KIZM-703"
tags = ["岡咲美保"]

[[discs]]
catalog = "KIZM-703"

[[discs.tracks]]
title = "ペタルズ"

[[discs.tracks]]
title = "好きじゃないよ"

[[discs.tracks]]
title = "魔法の言葉"

[[discs.tracks]]
title = "ペタルズ (off vocal version)"
type = "instrumental"

[[discs.tracks]]
title = "好きじゃないよ (off vocal version)"
type = "instrumental"

[[discs.tracks]]
title = "魔法の言葉 (off vocal version)"
type = "instrumental"

[[discs.tracks]]
title = "スペシャルボイスメッセージ"
type = "voice"
