[album]
album_id = "4ef391ac-7643-4504-a344-2fb20af2c713"
title = "THE IDOLM@STER LIVE THE@TER PERFORMANCE 02"
artist = "天海春香（中村繪里子）、天空橋朋花（小岩井ことり）、七尾百合子（伊藤美来）、箱崎星梨花（麻倉もも）、最上静香（田所あずさ）"
date = 2013-05-29
type = "normal"
catalog = "LACA-15300"
tags = ["THE IDOLM@STER LIVE THE@TER PERFORMANCE"]

[[discs]]
catalog = "LACA-15300"

[[discs.tracks]]
title = "ドラマパート1 ｢765ライブシアター開幕！｣"
type = "drama"

[[discs.tracks]]
title = "キラメキ進行形"
artist = "天海春香（中村繪里子）"

[[discs.tracks]]
title = "ドラマパート2 ｢ステージパフォーマンス ～天海春香の場合～｣"
artist = "天海春香（中村繪里子）"
type = "drama"

[[discs.tracks]]
title = "透明なプロローグ"
artist = "七尾百合子（伊藤美来）"

[[discs.tracks]]
title = "ドラマパート3 ｢ステージパフォーマンス ～七尾百合子の場合～｣"
artist = "七尾百合子（伊藤美来）"
type = "drama"

[[discs.tracks]]
title = "トキメキの音符になって"
artist = "箱崎星梨花（麻倉もも）"

[[discs.tracks]]
title = "ドラマパート4 ｢ステージパフォーマンス ～箱崎星梨花の場合～｣"
artist = "箱崎星梨花（麻倉もも）"
type = "drama"

[[discs.tracks]]
title = "Maria Trap"
artist = "天空橋朋花（小岩井ことり）"

[[discs.tracks]]
title = "ドラマパート5 ｢ステージパフォーマンス ～天空橋朋花の場合～｣"
artist = "天空橋朋花（小岩井ことり）"
type = "drama"

[[discs.tracks]]
title = "Precious Grain"
artist = "最上静香（田所あずさ）"

[[discs.tracks]]
title = "ドラマパート6 ｢ステージパフォーマンス ～最上静香の場合～｣"
artist = "最上静香（田所あずさ）"
type = "drama"

[[discs.tracks]]
title = "Legend Girls!!"

[[discs.tracks]]
title = "ボーナスドラマ ｢楽屋トーク｣"
type = "drama"
