[album]
title = "「花咲くいろは」オリジナルサウンドトラック　『湯乃鷺メモリィズ』"
artist = "浜口史郎"
date = 2011-09-28
type = "absolute"
catalog = "LACA-9217"

[[discs]]
catalog = "LACA-9217"

[[discs.tracks]]
title = "始まりの音色"

[[discs.tracks]]
title = "微笑の空気"

[[discs.tracks]]
title = "微笑の空気～ふわりと～"

[[discs.tracks]]
title = "日常と平和の狭間で"

[[discs.tracks]]
title = "愉快の種"

[[discs.tracks]]
title = "夕焼けに溶け込む時間"

[[discs.tracks]]
title = "笑顔に至る時間"

[[discs.tracks]]
title = "綺麗な風が吹く"

[[discs.tracks]]
title = "余裕の心は油断の心"

[[discs.tracks]]
title = "そよ風になびく草のように"

[[discs.tracks]]
title = "前向きのココロ"

[[discs.tracks]]
title = "前向きのココロ～ちらりと～"

[[discs.tracks]]
title = "緩やかさは暖かさ"

[[discs.tracks]]
title = "優しい少女は引っ込み思案"

[[discs.tracks]]
title = "時を刻む場所"

[[discs.tracks]]
title = "ここがぼんぼり時"

[[discs.tracks]]
title = "空回るパッション"

[[discs.tracks]]
title = "熱意が動く時"

[[discs.tracks]]
title = "新しい存在感"

[[discs.tracks]]
title = "そんなことってあるんだ感"

[[discs.tracks]]
title = "迫る人、迫られる人"

[[discs.tracks]]
title = "この世には色んな人がいる"

[[discs.tracks]]
title = "陽気であれば大丈夫"

[[discs.tracks]]
title = "イラムカな時もある"

[[discs.tracks]]
title = "空気読まんかい"

[[discs.tracks]]
title = "気持ちのスピードがちょっと遅い時"

[[discs.tracks]]
title = "弱くなった気持ち"

[[discs.tracks]]
title = "縛りのキツさよ"

[[discs.tracks]]
title = "徐々にそして段々と"

[[discs.tracks]]
title = "花いろ軍の行進"

[[discs.tracks]]
title = "戦いの後には感動がある"

[[discs.tracks]]
title = "懸命なる戦略会議"

[[discs.tracks]]
title = "これはさすがに疑う"

[[discs.tracks]]
title = "クライマックスに向かって叫べ!"
