[album]
album_id = "bfebf986-8daa-4b79-a582-9303793c07ee"
title = "THE IDOLM@STER MILLION THE@TER SEASON BRIGHT DIAMOND"
artist = "BRIGHT DIAMOND（伊吹翼（Machico）、徳川まつり（諏訪彩花）、四条貴音（原由実）、所恵美（藤井ゆきよ）、百瀬莉緒（山口立花子）、萩原雪歩（浅倉杏美）、田中琴葉（種田梨沙）、双海真美（下田麻美）、水瀬伊織（釘宮理恵）、宮尾美也（桐谷蝶々）、春日未来（山崎はるか）、桜守歌織（香里有佐）、周防桃子（渡部恵子））"
date = 2021-10-27
type = "normal"
catalog = "LACA-15916"
tags = ["THE IDOLM@STER MILLION THE@TER SEASON"]

[[discs]]
catalog = "LACA-15916"

[[discs.tracks]]
title = "ドラマ『最終公演一日目、その前に』"
type = "drama"

[[discs.tracks]]
title = "ダイヤモンド・クラリティ"

[[discs.tracks]]
title = "ドラマ『MC1』"
type = "drama"

[[discs.tracks]]
title = "DIAMOND JOKER"
artist = "伊吹翼（Machico）、徳川まつり（諏訪彩花）、四条貴音（原由実）、所恵美（藤井ゆきよ）"

[[discs.tracks]]
title = "ドラマ『バックステ一ジ1～MC2』"
type = "drama"

[[discs.tracks]]
title = "真夏のダイヤ☆"
artist = "百瀬莉緒（山口立花子）、萩原雪歩（浅倉杏美）、田中琴葉（種田梨沙）、双海真美（下田麻美）"

[[discs.tracks]]
title = "ドラマ『バックステ一ジ2』"
type = "drama"

[[discs.tracks]]
title = "シークレットジュエル ～魅惑の金剛石～"
artist = "水瀬伊織（釘宮理恵）、宮尾美也（桐谷蝶々）、春日未来（山崎はるか）、桜守歌織（香里有佐）、周防桃子（渡部恵子）"

[[discs.tracks]]
title = "ドラマ『MC3～また、明日も!』"
type = "drama"

[[discs.tracks]]
title = "Harmony 4 You"
