[album]
album_id = "ce6e2659-352f-4590-891c-7a0293494fa3"
title = "THE IDOLM@STER LIVE THE@TER HARMONY 02"
artist = "乙女ストーム！（春日未来（山崎はるか）、伊吹翼（Machico）、七尾百合子（伊藤美来）、真壁瑞希（阿部里果）、望月杏奈（夏川椎菜））"
date = 2014-07-30
type = "normal"
catalog = "LACA-15432"
tags = ["THE IDOLM@STER LIVE THE@TER HARMONY"]

[[discs]]
catalog = "LACA-15432"

[[discs.tracks]]
title = "Growing Storm!"

[[discs.tracks]]
title = "...In The Name Of。 ...LOVE?"
artist = "真壁瑞希（阿部里果）"

[[discs.tracks]]
title = "VIVID イマジネーション"
artist = "望月杏奈（夏川椎菜）"

[[discs.tracks]]
title = "空想文学少女"
artist = "七尾百合子（伊藤美来）"

[[discs.tracks]]
title = "Believe my change!"
artist = "伊吹翼（Machico）"

[[discs.tracks]]
title = "未来飛行"
artist = "春日未来（山崎はるか）"

[[discs.tracks]]
title = "Welcome!!"
