[album]
title = "「花咲くいろは」オリジナルサウンドトラック　『湯乃鷺メモリィズ』"
artist = "浜口史郎"
date = 2011-09-28
type = "absolute"
catalog = "LACA-9218"

[[discs]]
catalog = "LACA-9218"

[[discs.tracks]]
title = "妄想は個人の自由"

[[discs.tracks]]
title = "騒がしくて楽しい時"

[[discs.tracks]]
title = "軽快なムード"

[[discs.tracks]]
title = "グイグイ進め"

[[discs.tracks]]
title = "遠い目で考える"

[[discs.tracks]]
title = "想いを告げる難しさ"

[[discs.tracks]]
title = "不器用な乙女ほど美しく"

[[discs.tracks]]
title = "考えの果ては夢の中"

[[discs.tracks]]
title = "郷愁という気持ち～from ハナノイロ～"

[[discs.tracks]]
title = "悲しさは曇り空に似てる"

[[discs.tracks]]
title = "想いは言葉にしたらいい"

[[discs.tracks]]
title = "募る想いと悲しさは裏表"

[[discs.tracks]]
title = "解放されていく感情"

[[discs.tracks]]
title = "一生懸命さの時間"

[[discs.tracks]]
title = "受け止めてくれる優しさ～from ハナノイロ～"

[[discs.tracks]]
title = "笑顔で思い出せるあの日のこと"

[[discs.tracks]]
title = "氷が優しく溶けるように分かり合う"

[[discs.tracks]]
title = "新しい時間に出会える喜び"

[[discs.tracks]]
title = "文化の違いは生活の違い"

[[discs.tracks]]
title = "アイディアがまとまっていく瞬間"

[[discs.tracks]]
title = "行動する少女たち"

[[discs.tracks]]
title = "綺麗な気持ちになりました"

[[discs.tracks]]
title = "安心感は嬉しさに繋がる"

[[discs.tracks]]
title = "Ray of Light"

[[discs.tracks]]
title = "祭りの時"

[[discs.tracks]]
title = "懐かしさは微笑みをもたらす"

[[discs.tracks]]
title = "嬉しさ優しさ暖かさ"

[[discs.tracks]]
title = "不安の脈動"

[[discs.tracks]]
title = "ぼんぼり夜"
