[album]
title = "THE IDOLM@STER MILLION LIVE! M@STER SPARKLE 08"
artist = "北上麗花（平山笑美）、島原エレナ（角元明日香）、田中琴葉（種田梨沙）、天空橋朋花（小岩井ことり）"
date = 2018-04-04
type = "normal"
catalog = "LACA-15678"

[[discs]]
catalog = "LACA-15678"

[[discs.tracks]]
title = "シャクネツのパレード"
artist = "島原エレナ（角元明日香）"

[[discs.tracks]]
title = "空に手が触れる場所"
artist = "北上麗花（平山笑美）"

[[discs.tracks]]
title = "Sister"
artist = "天空橋朋花（小岩井ことり）"

[[discs.tracks]]
title = "シルエット"
artist = "田中琴葉（種田梨沙）"

[[discs.tracks]]
title = "Brand New Theater!"
artist = "765 MILLION ALLSTARS"
