[album]
title = "THE IDOLM@STER LIVE THE@TER PERFORMANCE 07"
artist = "三浦あずさ（たかはし智秋）、篠宮可憐（近藤唯）、髙山紗代子（駒形友梨）、福田のり子（浜崎奈々）"
date = 2013-10-30
type = "normal"
catalog = "LACA-15317"
tags = ["THE IDOLM@STER LIVE THE@TER PERFORMANCE"]

[[discs]]
catalog = "LACA-15317"

[[discs.tracks]]
title = "ドラマパート1 ｢765ライブシアター開幕～１週間前｣"
type = "drama"

[[discs.tracks]]
title = "ドラマパート2 ｢765ライブシアター開幕！｣"
type = "drama"

[[discs.tracks]]
title = "マイペース☆マイウェイ"
artist = "福田のり子（浜崎奈々）"

[[discs.tracks]]
title = "ドラマパート3 ｢ステージパフォーマンス ～福田のり子の場合～｣"
artist = "福田のり子（浜崎奈々）"
type = "drama"

[[discs.tracks]]
title = "君想いBirthday"
artist = "髙山紗代子（駒形友梨）"

[[discs.tracks]]
title = "ドラマパート4 ｢ステージパフォーマンス ～高山紗代子の場合～｣"
artist = "髙山紗代子（駒形友梨）"
type = "drama"

[[discs.tracks]]
title = "ちいさな恋の足音"
artist = "篠宮可憐（近藤唯）"

[[discs.tracks]]
title = "ドラマパート5 ｢ステージパフォーマンス ～篠宮可憐の場合～｣"
artist = "篠宮可憐（近藤唯）"
type = "drama"

[[discs.tracks]]
title = "嘆きのFRACTION"
artist = "三浦あずさ（たかはし智秋）"

[[discs.tracks]]
title = "ドラマパート6 ｢ステージパフォーマンス ～三浦あずさの場合～｣"
artist = "三浦あずさ（たかはし智秋）"
type = "drama"

[[discs.tracks]]
title = "カワラナイモノ"

[[discs.tracks]]
title = "ボーナスドラマ ｢楽屋トーク｣"
type = "drama"
