[album]
title = "THE IDOLM@STER MILLION LIVE! M@STER SPARKLE 01"
artist = "春日未来（山崎はるか）、白石紬（南早紀）、周防桃子（渡部恵子）、豊川風花（末柄里恵）、七尾百合子（伊藤美来）"
date = 2017-08-23
type = "normal"
catalog = "LACA-15671"
tags = ["THE IDOLM@STER MILLION LIVE! M@STER SPARKLE"]

[[discs]]
catalog = "LACA-15671"

[[discs.tracks]]
title = "ローリング△さんかく"
artist = "周防桃子（渡部恵子）"

[[discs.tracks]]
title = "地球儀にない国"
artist = "七尾百合子（伊藤美来）"

[[discs.tracks]]
title = "祈りの羽根"
artist = "豊川風花（末柄里恵）"

[[discs.tracks]]
title = "瑠璃色金魚と花菖蒲"
artist = "白石紬（南早紀）"

[[discs.tracks]]
title = "未来系ドリーマー"
artist = "春日未来（山崎はるか）"
