[album]
title = "THE IDOLM@STER MILLION LIVE! M@STER SPARKLE 05"
artist = "大神環（稲川英里）、宮尾美也（桐谷蝶々）、百瀬莉緒（山口立花子）、エミリー スチュアート（郁原ゆう）、真壁瑞希（阿部里果）"
date = 2018-01-10
type = "normal"
catalog = "LACA-15675"

[[discs]]
catalog = "LACA-15675"

[[discs.tracks]]
title = "Border LINE→→→♡"
artist = "百瀬莉緒（山口立花子）"

[[discs.tracks]]
title = "ふわりずむ"
artist = "宮尾美也（桐谷蝶々）"

[[discs.tracks]]
title = "たんけんぼうけん☆ハイホー隊"
artist = "大神環（稲川英里）"

[[discs.tracks]]
title = "Silent Joker"
artist = "真壁瑞希（阿部里果）"

[[discs.tracks]]
title = "はなしらべ"
artist = "エミリー スチュアート（郁原ゆう）"
