[album]
album_id = "8ddf2645-e075-4aaf-819d-c216c7e63ac4"
title = "THE IDOLM@STER LIVE THE@TER PERFORMANCE 05"
artist = "水瀬伊織（釘宮理恵）、エミリー スチュアート（郁原ゆう）、百瀬莉緒（山口立花子）、真壁瑞希（阿部里果）"
date = 2013-08-28
type = "normal"
catalog = "LACA-15315"
tags = ["THE IDOLM@STER LIVE THE@TER PERFORMANCE"]

[[discs]]
catalog = "LACA-15315"

[[discs.tracks]]
title = "ドラマパート1 ｢765ライブシアター開幕～１時間前｣"
type = "drama"

[[discs.tracks]]
title = "ドラマパート2 ｢765ライブシアター開幕！｣"
type = "drama"

[[discs.tracks]]
title = "微笑み日和"
artist = "エミリー スチュアート（郁原ゆう）"

[[discs.tracks]]
title = "ドラマパート3 ｢ステージパフォーマンス ～エミリー スチュアートの場合～｣"
artist = "エミリー スチュアート（郁原ゆう）"
type = "drama"

[[discs.tracks]]
title = "POKER POKER"
artist = "真壁瑞希（阿部里果）"

[[discs.tracks]]
title = "ドラマパート4 ｢ステージパフォーマンス ～真壁瑞希の場合～｣"
artist = "真壁瑞希（阿部里果）"
type = "drama"

[[discs.tracks]]
title = "Be My Boy"
artist = "百瀬莉緒（山口立花子）"

[[discs.tracks]]
title = "ドラマパート5 ｢ステージパフォーマンス ～百瀬莉緒の場合～｣"
artist = "百瀬莉緒（山口立花子）"
type = "drama"

[[discs.tracks]]
title = "プライヴェイト・ロードショウ (playback, Weekday)"
artist = "水瀬伊織（釘宮理恵）"

[[discs.tracks]]
title = "ドラマパート6 ｢ステージパフォーマンス ～水瀬伊織の場合～｣"
artist = "水瀬伊織（釘宮理恵）"
type = "drama"

[[discs.tracks]]
title = "Sentimental Venus"

[[discs.tracks]]
title = "ボーナスドラマ ｢楽屋トーク｣"
type = "drama"
