[album]
album_id = "cdc8dc02-c13d-4cae-9431-52c8f98fab88"
title = "THE IDOLM@STER LIVE THE@TER HARMONY 03"
artist = "クレシェンドブルー（最上静香（田所あずさ）、北上麗花（平山笑美）、北沢志保（雨宮天）、野々原茜（小笠原早紀）、箱崎星梨花（麻倉もも））"
date = 2014-09-24
type = "normal"
catalog = "LACA-15433"
tags = ["THE IDOLM@STER LIVE THE@TER HARMONY"]

[[discs]]
catalog = "LACA-15433"

[[discs.tracks]]
title = "Shooting Stars"

[[discs.tracks]]
title = "夢色トレイン"
artist = "箱崎星梨花（麻倉もも）"

[[discs.tracks]]
title = "サマ☆トリ ~Summer trip~"
artist = "北上麗花（平山笑美）"

[[discs.tracks]]
title = "プリティ～～～ッ→ニャンニャンッ！"
artist = "野々原茜（小笠原早紀）"

[[discs.tracks]]
title = "絵本"
artist = "北沢志保（雨宮天）"

[[discs.tracks]]
title = "Catch my dream"
artist = "最上静香（田所あずさ）"

[[discs.tracks]]
title = "Welcome!!"
