[album]
title = "THE IDOLM@STER LIVE THE@TER PERFORMANCE 08"
artist = "高槻やよい（仁後真耶子）、大神環（稲川英里）、中谷育（原嶋あかり）、矢吹可奈（木戸衣吹）"
date = 2013-11-27
type = "normal"
catalog = "LACA-15318"

[[discs]]
catalog = "LACA-15318"

[[discs.tracks]]
title = "ドラマパート1 ｢765ライブシアター開幕～10日前｣"
type = "drama"

[[discs.tracks]]
title = "ドラマパート2 ｢765ライブシアター開幕！｣"
type = "drama"

[[discs.tracks]]
title = "ホップ♪ステップ♪レインボウ♪"
artist = "大神環（稲川英里）"

[[discs.tracks]]
title = "ドラマパート3 ｢ステージパフォーマンス ～大神 環の場合～｣"
artist = "大神環（稲川英里）"
type = "drama"

[[discs.tracks]]
title = "グッデイ・サンシャイン！"
artist = "中谷育（原嶋あかり）"

[[discs.tracks]]
title = "ドラマパート4 ｢ステージパフォーマンス ～中谷 育の場合～｣"
artist = "中谷育（原嶋あかり）"
type = "drama"

[[discs.tracks]]
title = "オリジナル声になって"
artist = "矢吹可奈（木戸衣吹）"

[[discs.tracks]]
title = "ドラマパート5 ｢ステージパフォーマンス ～矢吹可奈の場合～｣"
artist = "矢吹可奈（木戸衣吹）"
type = "drama"

[[discs.tracks]]
title = "ハートウォーミング"
artist = "高槻やよい（仁後真耶子）"

[[discs.tracks]]
title = "ドラマパート6 ｢ステージパフォーマンス ～高槻やよいの場合～｣"
artist = "高槻やよい（仁後真耶子）"
type = "drama"

[[discs.tracks]]
title = "Good-Sleep, Baby♡"

[[discs.tracks]]
title = "ボーナスドラマ ｢楽屋トーク｣"
type = "drama"
