[album]
album_id = "d7be721e-955b-4b7b-8409-a25cb26c360d"
title = "THE IDOLM@STER LIVE THE@TER PERFORMANCE 06"
artist = "星井美希（長谷川明子）、伊吹翼（Machico）、北上麗花（平山笑美）、ジュリア（寺川愛美）"
date = 2013-09-25
type = "normal"
catalog = "LACA-15316"
tags = ["THE IDOLM@STER LIVE THE@TER PERFORMANCE"]

[[discs]]
catalog = "LACA-15316"

[[discs.tracks]]
title = "ドラマパート1 ｢765ライブシアター開幕～１時間前｣"
type = "drama"

[[discs.tracks]]
title = "ドラマパート2 ｢765ライブシアター開幕！｣"
type = "drama"

[[discs.tracks]]
title = "恋のLesson初級編"
artist = "伊吹翼（Machico）"

[[discs.tracks]]
title = "ドラマパート3 ｢ステージパフォーマンス ～伊吹翼の場合～｣"
artist = "伊吹翼（Machico）"
type = "drama"

[[discs.tracks]]
title = "FIND YOUR WIND！"
artist = "北上麗花（平山笑美）"

[[discs.tracks]]
title = "ドラマパート4 ｢ステージパフォーマンス ～北上麗花の場合～｣"
artist = "北上麗花（平山笑美）"
type = "drama"

[[discs.tracks]]
title = "追憶のサンドグラス"
artist = "星井美希（長谷川明子）"

[[discs.tracks]]
title = "ドラマパート5 ｢ステージパフォーマンス ～星井美希の場合～｣"
artist = "星井美希（長谷川明子）"
type = "drama"

[[discs.tracks]]
title = "流星群"
artist = "ジュリア（寺川愛美）"

[[discs.tracks]]
title = "ドラマパート6 ｢ステージパフォーマンス ～ジュリアの場合～｣"
artist = "ジュリア（寺川愛美）"
type = "drama"

[[discs.tracks]]
title = "Marionetteは眠らない"

[[discs.tracks]]
title = "ボーナスドラマ ｢楽屋トーク｣"
type = "drama"
