[album]
title = "THE IDOLM@STER MILLION RADIO! DJCD Vol.01"
artist = "春日未来（山崎はるか）、最上静香（田所あずさ）、箱崎星梨花（麻倉もも）"
date = 2015-08-26
type = "drama"
catalog = "LACA-15501"
tags = ["THE IDOLM@STER MILLION RADIO!"]

[[discs]]
catalog = "LACA-15501"

[[discs.tracks]]
title = "OPトーク"

[[discs.tracks]]
title = "2周年のご褒美は…?"

[[discs.tracks]]
title = "スペシャルコーナー"

[[discs.tracks]]
title = "スタジオにお返しします"

[[discs.tracks]]
title = "ミリオンライブ オーディオルーム"

[[discs.tracks]]
title = "Welcome!! -MR remix-"
type = "normal"

[[discs.tracks]]
title = "ゲストコーナー"

[[discs.tracks]]
title = "ミリオンリサーチ"

[[discs.tracks]]
title = "EDトーク"
