[album]
album_id = "c4d5234b-696e-447c-aa13-17ed74b9c547"
title = "THE IDOLM@STER SHINY COLORS GR@DATE WING 03"
artist = "アンティーカ"
date = 2020-11-04
type = "normal"
catalog = "LACM-14984"
tags = ["アンティーカ", "THE IDOLM@STER SHINY COLORS GR@DATE WING"]

[[discs]]
catalog = "LACM-14984"

[[discs.tracks]]
title = "Black Reverie"

[[discs.tracks]]
title = "純白トロイメライ"

[[discs.tracks]]
title = "シャイノグラフィ（アンティーカVer.）"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「雨の日にステップを」"
artist = "月岡恋鐘（礒部花凜）、田中摩美々（菅沼千紗）、白瀬咲耶（八巻アンナ）、三峰結華（成海瑠奈）、幽谷霧子（結名美月）"
type = "drama"
