[album]
title = "THE IDOLM@STER LIVE THE@TER PERFORMANCE 01"
artist = "765 MILLIONSTARS "
date = 2013-04-24
type = "normal"
catalog = "LACM-14080"

[[discs]]
catalog = "LACM-14080"

[[discs.tracks]]
title = "Thank You! （『アイドルマスター ミリオンライブ！』テーマソング）"

[[discs.tracks]]
title = "Thank You! (765PRO ver.)"

[[discs.tracks]]
title = "Thank You! (765THEATER ver.)"

[[discs.tracks]]
title = "Thank You! (Off Vocal)"
type = "instrumental"
