[album]
album_id = "c64d85ba-b314-4065-ae7b-2443fb478cdd"
title = "THE IDOLM@STER SHINY COLORS FR@GMENT WING 03"
artist = "アンティーカ"
date = 2019-06-12
type = "normal"
catalog = "LACM-14863"
tags = ["アンティーカ", "THE IDOLM@STER SHINY COLORS FR@GMENT WING"]

[[discs]]
catalog = "LACM-14863"

[[discs.tracks]]
title = "NEO THEORY FANTASY"

[[discs.tracks]]
title = "ラビリンス・レジスタンス"

[[discs.tracks]]
title = "Ambitious Eve（アンティーカ Ver.）"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「千変万化のアンティーカ」"
artist = "月岡恋鐘（礒部花凜）、田中摩美々（菅沼千紗）、白瀬咲耶（八巻アンナ）、三峰結華（成海瑠奈）、幽谷霧子（結名美月）"
type = "drama"
