[album]
album_id = "febae48e-62b8-49c9-bb98-8dbd1af51d13"
title = "たゆたえ、七色"
artist = "ARCANA PROJECT（桜野羽咲、空野青空、相田詩音、花宮ハナ、天野ひかる）"
date = 2021-07-14
type = "normal"
catalog = "LACM-24137"
tags = ["ARCANA PROJECT", "白い砂のアクアトープ"]

[[discs]]
catalog = "LACM-24137"

[[discs.tracks]]
title = "たゆたえ、七色"

[[discs.tracks]]
title = "星影のファンタジア"
