[album]
album_id = "262be5f8-de3a-4611-8f0b-ac73f8edf8e7"
title = "THE IDOLM@STER MILLION RADIO! ターンオンタイム！"
artist = "春日未来（山崎はるか）、最上静香（田所あずさ）、箱崎星梨花（麻倉もも）"
date = 2016-08-10
type = "normal"
catalog = "LACM-14506"
tags = ["THE IDOLM@STER MILLION RADIO!"]

[[discs]]
catalog = "LACM-14506"

[[discs.tracks]]
title = "ターンオンタイム！"

[[discs.tracks]]
title = "Dreaming! -MR remix-"

[[discs.tracks]]
title = "ミリラジ劇場 特別編 ～なにがでるかな？～"
type = "drama"

[[discs.tracks]]
title = "ターンオンタイム！ (Off Vocal)"

[[discs.tracks]]
title = "Dreaming! -MR remix- (Off Vocal)"
