[album]
album_id = "9a0efed1-c1eb-42f9-9d11-49d718494055"
title = "THE IDOLM@STER SHINY COLORS SWEET♡STEP"
artist = "シャイニーカラーズ"
date = 2020-02-12
type = "normal"
catalog = "LACM-14965"
tags = ["THE IDOLM@STER Shiny Colors"]

[[discs]]
catalog = "LACM-14965"

[[discs.tracks]]
title = "SWEET♡STEP"

[[discs.tracks]]
title = "Multicolored Sky -19 colors-"
