[album]
album_id = "ef15ee2d-8af2-41ed-912b-e06ae1b3612d"
title = "THE IDOLM@STER SHINY COLORS GR@DATE WING 05"
artist = "アルストロメリア"
date = 2020-12-09
type = "normal"
catalog = "LACM-14986"
tags = ["アルストロメリア", "THE IDOLM@STER SHINY COLORS GR@DATE WING"]

[[discs]]
catalog = "LACM-14986"

[[discs.tracks]]
title = "ダブル・イフェクト"

[[discs.tracks]]
title = "Anniversary"

[[discs.tracks]]
title = "シャイノグラフィ（アルストロメリアVer.）"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「グッド☆モーニング」"
artist = "大崎甘奈（黒木ほの香）、大崎甜花（前川涼子）、桑山千雪（芝崎典子）"
type = "drama"
