[album]
title = "THE IDOLM@STER MILLION THE@TER WAVE 04 Sherry 'n Cherry"
artist = "Sherry 'n Cherry（馬場このみ（高橋未奈美）、百瀬莉緒（山口立花子））"
date = 2019-12-25
type = "normal"
catalog = "LACM-14894"
tags = ["THE IDOLM@STER MILLION THE@TER WAVE"]

[[discs]]
catalog = "LACM-14894"

[[discs.tracks]]
title = "ドラマ『このみと莉緒のセクシー♡ナイトラジオ オープニング』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『セクシー♡ナイトラジォゲストコーナー ～その1』"
type = "drama"

[[discs.tracks]]
title = "Cherry Colored Love"

[[discs.tracks]]
title = "ドラマ『～収録の合間に～その1』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『セクシー♡ナイトラジオ ゲストコーナー ～その2』"
type = "drama"

[[discs.tracks]]
title = "夜と、明かりと。"

[[discs.tracks]]
title = "ドラマ『～収録の合間に～その2』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『セクシー♡ナイトラジオ エンディング』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『～収録の後で～』"
type = "drama"
