[album]
title = "THE IDOLM@STER SHINY COLORS FR@GMENT WING 05"
artist = "アルストロメリア"
date = 2019-08-21
type = "normal"
catalog = "LACM-14865"
tags = ["アルストロメリア", "THE IDOLM@STER SHINY COLORS FR@GMENT WING"]

[[discs]]
catalog = "LACM-14865"

[[discs.tracks]]
title = "Bloomy!"

[[discs.tracks]]
title = "Love Addiction"

[[discs.tracks]]
title = "Ambitious Eve（アルストロメリア Ver.）"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「つないだ手と手」"
artist = "大崎甘奈（黒木ほの香）、大崎甜花（前川涼子）、桑山千雪（芝崎典子）"
type = "drama"
