[album]
album_id = "8c15d517-b5af-43d5-a319-9d839819e32b"
title = "とめどない潮騒に僕たちは何を歌うだろうか"
artist = "ARCANA PROJECT（桜野羽咲、空野青空、相田詩音、花宮ハナ、天野ひかる）"
date = 2021-10-27
type = "normal"
catalog = "LACM-24204"
tags = ["ARCANA PROJECT", "白い砂のアクアトープ"]

[[discs]]
catalog = "LACM-24204"

[[discs.tracks]]
title = "とめどない潮騒に僕たちは何を歌うだろうか"

[[discs.tracks]]
title = "迷わないConquest"
