[album]
album_id = "b989a93c-8b37-4e17-822a-2783efaafd98"
title = "THE IDOLM@STER SHINY COLORS SE@SONAL WINTER"
artist = "シャイニーカラーズ"
date = 2018-12-19
type = "normal"
catalog = "LACM-14820"
tags = ["THE IDOLM@STER Shiny Colors"]

[[discs]]
catalog = "LACM-14820"

[[discs.tracks]]
title = "SNOW FLAKES MEMORIES"

[[discs.tracks]]
title = "Let's get a chance"
