[album]
album_id = "0146e931-4ae6-457a-a267-fad77c994b5d"
title = "八百万の島の唄／Dear My MAJIHA Sisters"
artist = "Various Artists"
date = 2021-09-29
type = "normal"
catalog = "LACM-24173"
tags = ["100万の命の上に俺は立っている"]

[[discs]]
catalog = "LACM-24173"

[[discs.tracks]]
title = "八百万の島の唄"
artist = "ヤーナ（竹達彩奈）、アォユー（悠木碧）"

[[discs.tracks]]
title = "Dear My MAJIHA Sisters"
artist = "マジハパープル（高槻かなこ）、マジハピンク（降幡愛）"

[[discs.tracks]]
title = "八百万の島の唄 (Instrumental)"
artist = "ヤーナ（竹達彩奈）、アォユー（悠木碧）"
type = "instrumental"

[[discs.tracks]]
title = "Dear My MAJIHA Sisters (Instrumental)"
artist = "マジハパープル（高槻かなこ）、マジハピンク（降幡愛）"
type = "instrumental"
