[album]
title = "THE IDOLM@STER MILLION THE@TER WAVE 02 Chrono-Lexica"
artist = "Chrono-Lexica（七尾百合子（伊藤美来）、永吉昴（斉藤佑圭）、ロコ（中村温姫）、望月杏奈（夏川椎菜）、真壁瑞希（阿部里果））"
date = 2019-08-28
type = "normal"
catalog = "LACM-14892"
tags = ["THE IDOLM@STER MILLION THE@TER WAVE"]

[[discs]]
catalog = "LACM-14892"

[[discs.tracks]]
title = "dans l'obscurité"

[[discs.tracks]]
title = "プロローグ～始まりのSabbath"
type = "drama"

[[discs.tracks]]
title = "少女たちの断章Ⅰ"
type = "drama"

[[discs.tracks]]
title = "少女たちの断章Ⅱ"
type = "drama"

[[discs.tracks]]
title = "囚われのTea Time"

[[discs.tracks]]
title = "エピローグ～そして少女たちは楽園へ向かう"
type = "drama"
