[album]
title = "THE IDOLM@STER SHINY COLORS GR@DATE WING 06"
artist = "ストレイライト"
date = 2020-08-19
type = "normal"
catalog = "LACM-14987"

[[discs]]
catalog = "LACM-14987"

[[discs.tracks]]
title = "Hide & Attack"

[[discs.tracks]]
title = "Destined Rival"

[[discs.tracks]]
title = "シャイノグラフィ（ストレイライトVer.）"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「ホット・リレイション」"
artist = "芹沢あさひ（田中有紀）、黛冬優子（幸村恵理）、和泉愛依（北原沙弥香）"
type = "drama"
