[album]
title = "THE IDOLM@STER LIVE THE@TER DREAMERS 06"
artist = "大神環（稲川英里）、双海真美（下田麻美）、菊地真（平田宏美）、舞浜歩（戸田めぐみ）、高坂海美（上田麗奈）、田中琴葉（種田梨沙）、島原エレナ（角元明日香）、星井美希（長谷川明子）、永吉昴（斉藤佑圭）、福田のり子（浜崎奈々）"
date = 2016-03-23
type = "normal"
catalog = "LACM-14416"
tags = ["THE IDOLM@STER LIVE THE@TER DREAMERS"]

[[discs]]
catalog = "LACM-14416"

[[discs.tracks]]
title = "765PRO LIVE THE@TER 幕張公演前日"
type = "drama"

[[discs.tracks]]
title = "Dreaming!"

[[discs.tracks]]
title = "765PRO LIVE THE@TER 幕張公演幕間"
type = "drama"

[[discs.tracks]]
title = "Understand? Understand!"
artist = "高坂海美（上田麗奈）、田中琴葉（種田梨沙）"

[[discs.tracks]]
title = "ジャングル☆パーティー"
artist = "大神環（稲川英里）、双海真美（下田麻美）"

[[discs.tracks]]
title = "Beat the World!!!"
artist = "菊地真（平田宏美）、舞浜歩（戸田めぐみ）"

[[discs.tracks]]
title = "Emergence Vibe"
artist = "島原エレナ（角元明日香）、星井美希（長谷川明子）"

[[discs.tracks]]
title = "Dreamscape"
artist = "永吉昴（斉藤佑圭）、福田のり子（浜崎奈々）"

[[discs.tracks]]
title = "765PRO LIVE THE@TER 幕張公演終演後"
type = "drama"
