[album]
title = "THE IDOLM@STER MILLION THE@TER GENERATION 04 プリンセススターズ"
artist = "プリンセススターズ（春日未来（山崎はるか）、徳川まつり（諏訪彩花）、矢吹可奈（木戸衣吹）、七尾百合子（伊藤美来）、エミリー スチュアート（郁原ゆう））"
date = 2018-01-31
type = "normal"
catalog = "LACM-14634"

[[discs]]
catalog = "LACM-14634"

[[discs.tracks]]
title = "Princess Be Ambitious!!"

[[discs.tracks]]
title = "Brand New Theater!"

[[discs.tracks]]
title = "ドラマパート「Princess Stars! -Other Side-」"
type = "drama"
