[album]
title = "パトリシア"
artist = "nano.RIPE"
date = 2010-09-22
type = "normal"
catalog = "LACM-4740"

[[discs]]
catalog = "LACM-4740"

[[discs.tracks]]
title = "パトリシア"

[[discs.tracks]]
title = "水性キャスト"

[[discs.tracks]]
title = "夢路"
