[album]
album_id = "7d96e154-1596-415b-a54c-95368339bcea"
title = "THE IDOLM@STER SHINY COLORS L@YERED WING 04"
artist = "放課後クライマックスガールズ"
date = 2021-07-14
type = "normal"
catalog = "LACM-24114"
tags = ["放課後クライマックスガールズ", "THE IDOLM@STER SHINY COLORS L@YERED WING"]

[[discs]]
catalog = "LACM-24114"

[[discs.tracks]]
title = "クライマックスアイランド"

[[discs.tracks]]
title = "拝啓タイムカプセル"

[[discs.tracks]]
title = "Resonance⁺（放課後クライマックスガールズ Ver.）"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「アタシらしく」"
type = "drama"

[[discs.tracks]]
title = "クライマックスアイランド（Off Vocal）"
type = "instrumental"

[[discs.tracks]]
title = "拝啓タイムカプセル（Off Vocal）"
type = "instrumental"
