[album]
title = "THE IDOLM@STER MILLION THE@TER GENERATION 17 STAR ELEMENTS"
artist = "STAR ELEMENTS（春日未来（山崎はるか）、矢吹可奈（木戸衣吹）、田中琴葉（種田梨沙））"
date = 2019-05-29
type = "normal"
catalog = "LACM-14827"
tags = ["THE IDOLM@STER MILLION THE@TER GENERATION"]

[[discs]]
catalog = "LACM-14827"

[[discs.tracks]]
title = "ドラマ『階のスターエレメンツ』プロローグ"
type = "drama"

[[discs.tracks]]
title = "Episode. Tiara"

[[discs.tracks]]
title = "ドラマ『階のスターエレメンツ』前編"
type = "drama"

[[discs.tracks]]
title = "ドラマ『階のスターエレメンツ』後編"
type = "drama"

[[discs.tracks]]
title = "ドラマ『階のスターエレメンツ』エピローグ"
type = "drama"

[[discs.tracks]]
title = "ギブミーメタファー"

[[discs.tracks]]
title = "エンディング"
type = "drama"
