[album]
title = "THE IDOLM@STER SHINY COLORS FR@GMENT WING 06"
artist = "ストレイライト"
date = 2019-09-11
type = "normal"
catalog = "LACM-14866"
tags = ["ストレイライト", "THE IDOLM@STER SHINY COLORS FR@GMENT WING"]

[[discs]]
catalog = "LACM-14866"

[[discs.tracks]]
title = "Wandering Dream Chaser"

[[discs.tracks]]
title = "Transcending The World"

[[discs.tracks]]
title = "Ambitious Eve（ストレイライト Ver.）"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「イーティング・エクスペディション」"
artist = "芹沢あさひ（田中有紀）、黛冬優子（幸村恵理）、和泉愛依（北原沙弥香）"
type = "drama"
