[album]
title = "sleepland"
artist = "上田麗奈"
date = 2018-02-07
type = "normal"
catalog = "LACM-14724"

[[discs]]
catalog = "LACM-14724"

[[discs.tracks]]
title = "sleepland"

[[discs.tracks]]
title = "誰もわたしを知らない世界へ"

[[discs.tracks]]
title = "fairy taleの明けに"
