[album]
album_id = "e084028b-43f6-4f2a-935c-bca5832fc0cc"
title = "THE IDOLM@STER MILLION THE@TER WAVE 03 Xs"
artist = "Xs（萩原雪歩（浅倉杏美）、星井美希（長谷川明子）、菊地真（平田宏美）、水瀬伊織（釘宮理恵））"
date = 2019-09-25
type = "normal"
catalog = "LACM-14893"
tags = ["THE IDOLM@STER MILLION THE@TER WAVE"]

[[discs]]
catalog = "LACM-14893"

[[discs.tracks]]
title = "ドラマ『ミッドナイト・ガールズ・パーティー』"
type = "drama"

[[discs.tracks]]
title = "ラビットファー"

[[discs.tracks]]
title = "ドラマ『小悪魔の誘惑』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『ガールズトーーーク！』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『おひとりさまパーティー？』"
type = "drama"

[[discs.tracks]]
title = "Dreamy Dream"

[[discs.tracks]]
title = "ドラマ『グンナイ、ガールズ』"
type = "drama"
