[album]
album_id = "dd958bed-1216-4679-bd9a-1df60d3c6708"
title = "THE IDOLM@STER LIVE THE@TER DREAMERS 02"
artist = "天海春香（中村繪里子）、春日未来（山崎はるか）、北上麗花（平山笑美）、北沢志保（雨宮天）、ジュリア（愛美）、高槻やよい（仁後真耶子）、所恵美（藤井ゆきよ）、七尾百合子（伊藤美来）、望月杏奈（夏川椎菜）、矢吹可奈（木戸衣吹）"
date = 2015-10-28
type = "normal"
catalog = "LACM-14412"
tags = ["THE IDOLM@STER LIVE THE@TER DREAMERS"]

[[discs]]
catalog = "LACM-14412"

[[discs.tracks]]
title = "Overture"
type = "drama"

[[discs.tracks]]
title = "Dreaming!"

[[discs.tracks]]
title = "765PRO LIVE THE@TER仙台公演開演！"
type = "drama"

[[discs.tracks]]
title = "ハルカナミライ"
artist = "天海春香（中村繪里子）、春日未来（山崎はるか）"

[[discs.tracks]]
title = "成長Chu→LOVER!!"
artist = "望月杏奈（夏川椎菜）、七尾百合子（伊藤美来）"

[[discs.tracks]]
title = "エスケープ"
artist = "ジュリア（愛美）、所恵美（藤井ゆきよ）"

[[discs.tracks]]
title = "Eternal Spiral"
artist = "高槻やよい（仁後真耶子）、矢吹可奈（木戸衣吹）"

[[discs.tracks]]
title = "piece of cake"
artist = "北上麗花（平山笑美）、北沢志保（雨宮天）"

[[discs.tracks]]
title = "Bonus Talk"
type = "drama"
