[album]
title = "THE IDOLM@STER MILLION THE@TER GENERATION 18 765PRO ALLSTARS"
artist = "765PRO ALLSTARS（天海春香（中村繪里子）、如月千早（今井麻美）、星井美希（長谷川明子）、秋月律子（若林直美）、我那覇響（沼倉愛美）、菊地真（平田宏美）、四条貴音（原由実）、高槻やよい（仁後真耶子）、萩原雪歩（浅倉杏美）、双海亜美（下田麻美）、双海真美（下田麻美）、三浦あずさ（たかはし智秋）、水瀬伊織（釘宮理恵））"
date = 2019-06-26
type = "normal"
catalog = "LACM-14828"
tags = ["THE IDOLM@STER MILLION THE@TER GENERATION"]

[[discs]]
catalog = "LACM-14828"

[[discs.tracks]]
title = "ドラマ『オーディションにて』"
type = "drama"

[[discs.tracks]]
title = "LEADER!!"

[[discs.tracks]]
title = "ドラマ『秘密の計画！？』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『それぞれの思い』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『新しい場所』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『私達の未来へ』"
type = "drama"

[[discs.tracks]]
title = "Brand New Theater!"
