[album]
album_id = "f59c10e4-bcd1-4031-9cef-be91ae4b76b3"
title = "THE IDOLM@STER SHINY COLORS BRILLI@NT WING 02 ヒカリのdestination"
artist = "イルミネーションスターズ"
date = 2018-07-04
type = "normal"
catalog = "LACM-14782"
tags = [
  "イルミネーションスターズ",
  "THE IDOLM@STER SHINY COLORS BRILLI@NT WING"
]

[[discs]]
catalog = "LACM-14782"

[[discs.tracks]]
title = "ヒカリのdestination"

[[discs.tracks]]
title = "虹になれ"

[[discs.tracks]]
title = "Spread the Wings!! (イルミネーションスターズ Ver.)"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「イルミネーションスターズ・イン・ストア」"
artist = "櫻木真乃（関根瞳）、風野灯織（近藤玲奈）、八宮めぐる（峯田茉優）"
type = "drama"
