[album]
title = "はなさくいろは"
artist = "クラムボン"
date = 2011-08-24
type = "normal"
catalog = "LACM-4849"

[[discs]]
catalog = "LACM-4849"

[[discs.tracks]]
title = "はなさくいろは"

[[discs.tracks]]
title = "いとすずしよへ"

[[discs.tracks]]
title = "はなさくいろは (TV SIZE)"

[[discs.tracks]]
title = "はなさくいろは (instrumental)"
type = "instrumental"
