[album]
album_id = "e23a818d-e7dc-4b86-8da0-a1fbd3331b39"
title = "THE IDOLM@STER MILLION THE@TER WAVE 18 ストロベリーポップムーン"
artist = "ストロベリーポップムーン（春日未来（山崎はるか）、最上静香（田所あずさ）、伊吹翼（Machico））"
date = 2021-06-23
type = "normal"
catalog = "LACM-24108"
tags = ["THE IDOLM@STER MILLION THE@TER WAVE"]

[[discs]]
catalog = "LACM-24108"

[[discs.tracks]]
title = "ドラマ『Stage01：はじまり』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『Stage02：ある遭遇』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『Stage03：選ばれること』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『Stage04：私たちのステージ！』"
type = "drama"

[[discs.tracks]]
title = "ABSOLUTE RUN!!!"

[[discs.tracks]]
title = "ドラマ『Stage05：頂点の、その先で』"
type = "drama"

[[discs.tracks]]
title = "Be proud"
