[album]
album_id = "b97678bc-2f12-4933-bc62-2b3e88e84b2f"
title = "Baddest"
artist = "樋口楓"
date = 2021-08-25
type = "normal"
catalog = "LACM-34125"
tags = ["樋口楓", "100万の命の上に俺は立っている"]

[[discs]]
catalog = "LACM-34125"

[[discs.tracks]]
title = "Baddest"

[[discs.tracks]]
title = "Sting or stung"

[[discs.tracks]]
title = "ikiteku."
