[album]
title = "Songbirds"
artist = "Homecomings"
date = 2018-04-25
type = "normal"
catalog = "LACM-14743"

[[discs]]
catalog = "LACM-14743"

[[discs.tracks]]
title = "Songbirds"

[[discs.tracks]]
title = "Play Yard Symphony [for New Neighbors]"

[[discs.tracks]]
title = "Songbirds [Miniascape sunset]"
