[album]
album_id = "91024f25-2dba-4c2c-9f0c-acd45189616e"
title = "THE IDOLM@STER SHINY COLORS L@YERED WING 08"
artist = "シーズ"
date = 2021-11-10
type = "normal"
catalog = "LACM-24118"
tags = ["シーズ", "THE IDOLM@STER SHINY COLORS L@YERED WING"]

[[discs]]
catalog = "LACM-24118"

[[discs.tracks]]
title = "OH MY GOD"

[[discs.tracks]]
title = "Fly and Fly"

[[discs.tracks]]
title = "Resonance⁺（シーズ Ver.）"

[[discs.tracks]]
title = "スペシャルオーディオドラマ「匣の中」"
type = "drama"

[[discs.tracks]]
title = "OH MY GOD（Off Vocal）"
type = "instrumental"

[[discs.tracks]]
title = "Fly and Fly（Off Vocal）"
type = "instrumental"
