[album]
album_id = "1bf29abe-f27c-45af-8337-eea76a21f1d5"
title = "THE IDOLM@STER THE@TER BOOST 01"
artist = "高坂海美（上田麗奈）、所恵美（藤井ゆきよ）、高山紗代子（駒形友梨）、豊川風花（末柄里恵）、横山奈緒（渡部優衣）"
date = 2018-09-26
type = "normal"
catalog = "LACM-14811"
tags = ["THE IDOLM@STER THE@TER BOOST"]

[[discs]]
catalog = "LACM-14811"

[[discs.tracks]]
title = "ドラマ『ビッグバンズバリボー!!!!!』／『プロローグ!!』"
type = "drama"

[[discs.tracks]]
title = "ビッグバンズバリボー!!!!!"

[[discs.tracks]]
title = "ドラマ『ビッグバンズバリボー!!!!!』／『激突!!帝花女学院!!』"
type = "drama"

[[discs.tracks]]
title = "DIAMOND DAYS"
