[album]
album_id = "2352c1c1-7335-4500-b767-66a9c6975332"
title = "THE IDOLM@STER SHINY COLORS FUTURITY SMILE"
artist = "シャイニーカラーズ"
date = 2019-12-18
type = "normal"
catalog = "LACM-14906"
tags = ["THE IDOLM@STER Shiny Colors"]

[[discs]]
catalog = "LACM-14906"

[[discs.tracks]]
title = "FUTURITY SMILE"

[[discs.tracks]]
title = "Spread the Wings!! -19 colors-"
