[album]
album_id = "48efadd4-e593-4e09-8a52-c4b6e5a5234d"
title = "THE IDOLM@STER MILLION RADIO! ENDLESS TOUR"
artist = "春日未来（山崎はるか）、最上静香（田所あずさ）、箱崎星梨花（麻倉もも）"
date = 2020-04-29
type = "normal"
catalog = "LACM-14961"
tags = ["THE IDOLM@STER MILLION RADIO!"]

[[discs]]
catalog = "LACM-14961"

[[discs.tracks]]
title = "ENDLESS TOUR"

[[discs.tracks]]
title = "Flyers!!! -MR remix-"
