[album]
album_id = "f60be247-ab87-4e5a-85b0-dcf419c28843"
title = "THE IDOLM@STER MILLION THE@TER WAVE 06 花咲夜"
artist = "花咲夜（エミリー スチュアート（郁原ゆう）、白石紬（南早紀）、天空橋朋花（小岩井ことり））"
date = 2020-02-26
type = "normal"
catalog = "LACM-14896"
tags = ["THE IDOLM@STER MILLION THE@TER WAVE"]

[[discs]]
catalog = "LACM-14896"

[[discs.tracks]]
title = "ドラマ『序の巻 おいでませ、忍者村！』"
type = "drama"

[[discs.tracks]]
title = "百花は月下に散りぬるを"

[[discs.tracks]]
title = "ドラマ『壱の巻 手裏剣の段』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『弐の巻 水蜘蛛の段』"
type = "drama"

[[discs.tracks]]
title = "ドラマ『跋の巻 新たなる密命』"
type = "drama"

[[discs.tracks]]
title = "矛盾の月"
