[album]
title = "THE IDOLM@STER MILLION THE@TER SEASON Harmony 4 You"
artist = "765 MILLION ALLSTARS"
date = 2021-07-28
type = "normal"
catalog = "LACM-24151"

[[discs]]
catalog = "LACM-24151"

[[discs.tracks]]
title = "Harmony 4 You"

[[discs.tracks]]
title = "EVERYDAY STARS!! (765PRO ALLSTARS ver.)"
artist = "765PRO ALLSTARS"

[[discs.tracks]]
title = "EVERYDAY STARS!! (プリンセススターズ ver.)"
artist = "プリンセススターズ"

[[discs.tracks]]
title = "EVERYDAY STARS!! (フェアリースターズ ver.)"
artist = "フェアリースターズ"

[[discs.tracks]]
title = "EVERYDAY STARS!! (エンジェルスターズ ver.)"
artist = "エンジェルスターズ"
