[album]
album_id = "86c34df8-4966-4b95-b67e-0a7c6422c75e"
title = "THE IDOLM@STER MILLION THE@TER GENERATION 11 UNION!!"
artist = "765 MILLION ALLSTARS"
date = 2018-08-29
type = "normal"
catalog = "LACM-14641"
tags = ["THE IDOLM@STER MILLION THE@TER GENERATION"]

[[discs]]
catalog = "LACM-14641"

[[discs.tracks]]
title = "UNION!!"

[[discs.tracks]]
title = "Welcome!!"

[[discs.tracks]]
title = "UNION!! (Off Vocal)"
type = "instrumental"

[[discs.tracks]]
title = "Welcome!! (Off Vocal)"
type = "instrumental"
