[album]
album_id = "9e7e79ff-4333-4c39-97f4-c91b4516e7e9"
title = "THE IDOLM@STER SHINY COLORS デビ太郎 VS ジャスティスV"
artist = "大崎甜花（前川涼子）、小宮果穂（河野ひより）"
date = 2020-07-29
type = "normal"
catalog = "LACZ-10033"
tags = ["THE IDOLM@STER Shiny Colors"]

[[discs]]
catalog = "LACZ-10033"

[[discs.tracks]]
title = "デビ太郎のうた"
artist = "大崎甜花（前川涼子）"

[[discs.tracks]]
title = "絶対正義 EVERY DAY"
artist = "小宮果穂（河野ひより）"
