[album]
album_id = "9c7f803a-5ab0-4445-8606-5150e7621903"
title = "THE IDOLM@STER MILLION RADIO! 765PRO LIVE THE@TER ミリラジ劇場セレクション ～アニメイト～"
artist = "春日未来（山崎はるか）、最上静香（田所あずさ）、箱崎星梨花（麻倉もも）"
date = 2014-06-04
type = "drama"
catalog = "LAPP-1063"
tags = ["THE IDOLM@STER MILLION RADIO!"]

[[discs]]
catalog = "LAPP-1063"

[[discs.tracks]]
title = "ミリラジ劇場 第1回「どうしたの？」"

[[discs.tracks]]
title = "ミリラジ劇場 第20回「まだまだ」"

[[discs.tracks]]
title = "ミリラジ劇場 第41回「どうしよう？」"
