[album]
title = "シークレットジュエル ～魅惑の金剛石～"
artist = "水瀬伊織（釘宮理恵）、宮尾美也（桐谷蝶々）、春日未来（山崎はるか）、桜守歌織（香里有佐）、周防桃子（渡部恵子）"
date = 2021-09-10
type = "normal"
catalog = "LZC-1940"

[[discs]]
catalog = "LZC-1940"

[[discs.tracks]]
title = "シークレットジュエル ～魅惑の金剛石～"
