[album]
title = "DIAMOND JOKER"
artist = "伊吹翼（Machico）、徳川まつり（諏訪彩花）、四条貴音（原由実）、所恵美（藤井ゆきよ）"
date = 2021-07-29
type = "normal"
catalog = "LZC-1938"

[[discs]]
catalog = "LZC-1938"

[[discs.tracks]]
title = "DIAMOND JOKER"
