[album]
album_id = "1753bb21-d429-4781-ab9a-4c83f355db99"
title = "THE IDOLM@STER LIVE THE@TER SOLO COLLECTION Vol.01"
artist = "Various Artists"
date = 2015-04-04
type = "normal"
catalog = "LZM-2124~5"
tags = ["THE IDOLM@STER LIVE THE@TER SOLO COLLECTION"]

[[discs]]
catalog = "LZM-2124"

[[discs.tracks]]
title = "Thank You! -MR Remix-"
artist = "箱崎星梨花（麻倉もも）"

[[discs.tracks]]
title = "Legend Girls!!"
artist = "七尾百合子（伊藤美来）"

[[discs.tracks]]
title = "PRETTY DREAMER"
artist = "望月杏奈（夏川椎菜）"

[[discs.tracks]]
title = "Blue Symphony"
artist = "北沢志保（雨宮天）"

[[discs.tracks]]
title = "Sentimental Venus"
artist = "百瀬莉緒（山口立花子）"

[[discs.tracks]]
title = "Marionetteは眠らない"
artist = "ジュリア（愛美）"

[[discs.tracks]]
title = "カワラナイモノ"
artist = "高山紗代子（駒形友梨）"

[[discs.tracks]]
title = "Helloコンチェルト"
artist = "松田亜利沙（村川梨衣）"

[[discs.tracks]]
title = "瞳の中のシリウス"
artist = "高坂海美（上田麗奈）"

[[discs.tracks]]
title = "Fu-Wa-Du-Wa"
artist = "舞浜歩（戸田めぐみ）"

[[discs.tracks]]
title = "Bigバルーン◎"
artist = "馬場このみ（高橋未奈美）"

[[discs]]
catalog = "LZM-2125"

[[discs.tracks]]
title = "Growing Storm!"
artist = "春日未来（山崎はるか）"

[[discs.tracks]]
title = "Shooting Stars"
artist = "最上静香（田所あずさ）"

[[discs.tracks]]
title = "Eternal Harmony"
artist = "豊川風花（末柄里恵）"

[[discs.tracks]]
title = "HOME, SWEET FRIENDSHIP"
artist = "横山奈緒（渡部優衣）"

[[discs.tracks]]
title = "ジレるハートに火をつけて"
artist = "所恵美（藤井ゆきよ）"

[[discs.tracks]]
title = "Birth of Color"
artist = "矢吹可奈（木戸衣吹）"

[[discs.tracks]]
title = "ドリームトラベラー"
artist = "佐竹美奈子（大関英里）"

[[discs.tracks]]
title = "星屑のシンフォニア"
artist = "天空橋朋花（小岩井ことり）"

[[discs.tracks]]
title = "STANDING ALIVE"
artist = "篠宮可憐（近藤唯）"

[[discs.tracks]]
title = "Welcome!!"
artist = "伊吹翼（Machico）"
