[album]
album_id = "3fb7c0bc-b1ce-4003-a4ec-9cf5bbef076c"
title = "Melody and Flower"
artist = "遠藤ゆりか"
date = 2017-04-26
type = "normal"
catalog = "PCCG-70367"
tags = ["遠藤ゆりか"]

[[discs]]
catalog = "PCCG-70367"

[[discs.tracks]]
title = "Melody and Flower"

[[discs.tracks]]
title = "knight-night."

[[discs.tracks]]
title = "Melody and Flower (instrumental)"
type = "instrumental"

[[discs.tracks]]
title = "knight-night. (instrumental)"
type = "instrumental"
