[album]
title = "夏の花火と君と青"
artist = "DIALOGUE+（内山悠里菜、稗田寧々、守屋亨香、緒方佑奈、鷹村彩花、宮原颯希、飯塚麻結、村上まなつ）"
date = 2020-12-23
type = "normal"
catalog = "PCSP-03303"

[[discs]]
catalog = "PCSP-03303"

[[discs.tracks]]
title = "夏の花火と君と青"

[[discs.tracks]]
title = "夏の花火と君と青 (Instrumental)"
type = "instrumental"
