[album]
album_id = "e915c8e2-77c3-464f-87a1-aad55f43b314"
title = "はじまりのうた"
artist = "遠藤ゆりか"
date = 2015-11-25
type = "normal"
catalog = "SCCG-00008"
tags = ["遠藤ゆりか"]

[[discs]]
catalog = "SCCG-00008"

[[discs.tracks]]
title = "はじまりのうた"

[[discs.tracks]]
title = "はじまりのうた (Instrumental)"
type = "instrumental"
