[album]
album_id = "18f110c1-4ceb-499a-95eb-bf22125489ff"
title = "君色シグナル"
edition = "期間生産限定盤"
artist = "春奈るな"
date = 2015-01-28
type = "normal"
catalog = "SECL-1635"
tags = ["春奈るな", "冴えない彼女の育てかた"]

[[discs]]
catalog = "SECL-1635"

[[discs.tracks]]
title = "君色シグナル"

[[discs.tracks]]
title = "トキメキ MY HEART"

[[discs.tracks]]
title = "青春プリンセス"

[[discs.tracks]]
title = "君色シグナル-TV size ver.-"
