[album]
title = "コネクト"
edition = "初回生産限定盤"
artist = "ClariS（クララ、アリス）"
date = 2011-02-02
type = "normal"
catalog = "SECL-946"
tags = ["ClariS"]

[[discs]]
catalog = "SECL-946"

[[discs.tracks]]
title = "コネクト"

[[discs.tracks]]
title = "Dreamin'"

[[discs.tracks]]
title = "キミとふたり"

[[discs.tracks]]
title = "コネクト -Instrumental-"
type = "instrumental"
