[album]
title = "Eternal"
artist = "雨宮天"
date = 2017-12-23
type = "normal"
catalog = "SMCL-521"

[[discs]]
catalog = "SMCL-521"

[[discs.tracks]]
title = "Eternal"

[[discs.tracks]]
title = "Marvelous scene"

[[discs.tracks]]
title = "Eternal (Instrumental)"
type = "instrumental"
