[album]
title = "誓い"
artist = "雨宮天"
date = 2018-05-09
type = "normal"
catalog = "SMCL-539"

[[discs]]
catalog = "SMCL-539"

[[discs.tracks]]
title = "誓い"

[[discs.tracks]]
title = "Abyss"

[[discs.tracks]]
title = "誓い (Instrumental)"
type = "instrumental"
