[album]
title = "トクベツいちばん!!"
artist = "麻倉もも"
date = 2017-06-17
type = "normal"
catalog = "SMCL-483"

[[discs]]
catalog = "SMCL-483"

[[discs.tracks]]
title = "トクベツいちばん!!"

[[discs.tracks]]
title = "箱庭ボーダーライン"

[[discs.tracks]]
title = "トクベツいちばん!! (Instrumental)"
type = "instrumental"
