[album]
title = "桜色ダイアリー"
artist = "妄想キャリブレーション"
date = 2017-06-14
type = "normal"
catalog = "SRCL-9417"

[[discs]]
catalog = "SRCL-9417"

[[discs.tracks]]
title = "桜色ダイアリー"

[[discs.tracks]]
title = "青春プロローグ"

[[discs.tracks]]
title = "スバラシキセカイ"

[[discs.tracks]]
title = "桜色ダイアリー -Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "青春プロローグ -Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "スバラシキセカイ -Instrumental-"
type = "instrumental"
