[album]
album_id = "c273663c-0e12-454d-b4ae-a47fd6bbff71"
title = "カラフル。"
edition = "期間生産限定盤"
artist = "沢井美空"
date = 2015-01-28
type = "normal"
catalog = "SRCL-8676"
tags = ["沢井美空", "冴えない彼女の育てかた"]

[[discs]]
catalog = "SRCL-8676"

[[discs.tracks]]
title = "カラフル。"

[[discs.tracks]]
title = "dim"

[[discs.tracks]]
title = "サヨナラの手前"

[[discs.tracks]]
title = "カラフル。（AnimeVer.）"

[[discs.tracks]]
title = "カラフル。（Instrumental）"
type = "instrumental"
