[album]
album_id = "db4c9225-196c-498d-bd5f-4ec3e50758ac"
title = "桜色ダイアリー"
edition = "期間生産限定盤（アニメ盤）"
artist = "妄想キャリブレーション（胡桃沢まひる、桜野羽咲、星野にぁ、雨宮伊織、水城夢子）"
date = 2017-06-14
type = "normal"
catalog = "SRCL-9417"
tags = ["妄想キャリブレーション", "冴えない彼女の育てかた♭"]

[[discs]]
catalog = "SRCL-9417"

[[discs.tracks]]
title = "桜色ダイアリー"

[[discs.tracks]]
title = "青春プロローグ"

[[discs.tracks]]
title = "スバラシキセカイ"
artist = "LAVILITH（相沢梨紗、桜野羽咲）"

[[discs.tracks]]
title = "桜色ダイアリー -Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "青春プロローグ -Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "スバラシキセカイ -Instrumental-"
artist = "LAVILITH"
type = "instrumental"
