[album]
title = "オリジナル。"
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
date = 2017-02-08
type = "normal"
catalog = "SVWC-70228"

[[discs]]
catalog = "SVWC-70228"

[[discs.tracks]]
title = "オリジナル。"

[[discs.tracks]]
title = "Chip log"

[[discs.tracks]]
title = "オリジナル。Instrumental"
type = "instrumental"

[[discs.tracks]]
title = "Chip log Instrumental"
type = "instrumental"
