[album]
title = "Sail Canvas"
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
date = 2016-05-25
type = "normal"
catalog = "SVWC-70161"

[[discs]]
catalog = "SVWC-70161"

[[discs.tracks]]
title = "Youthful Dreamer"

[[discs.tracks]]
title = "コバルト"

[[discs.tracks]]
title = "sewing dream"

[[discs.tracks]]
title = "Baby My Step"

[[discs.tracks]]
title = "primary"

[[discs.tracks]]
title = "明日も晴れる"

[[discs.tracks]]
title = "パーリー☆パーティ"

[[discs.tracks]]
title = "ホントだよ"

[[discs.tracks]]
title = "whiz"

[[discs.tracks]]
title = "あかね色"

[[discs.tracks]]
title = "Sail Out"

[[discs.tracks]]
title = "ひかるカケラ"
