[album]
title = "リア獣ハンター優子 AN ORIGINAL SOUNDTRACK everlasting force"
artist = "柳英一朗"
date = 2010-10-26
type = "absolute"
catalog = "SW-059ST"

[[discs]]
catalog = "SW-059ST"

[[discs.tracks]]
title = "Two, Only Two - ちーかま Style -"

[[discs.tracks]]
title = "悠久のバトル!"

[[discs.tracks]]
title = "その辺を歩く"

[[discs.tracks]]
title = "風駆ける翼"

[[discs.tracks]]
title = "夕焼け空に浮かぶ月"

[[discs.tracks]]
title = "リア獣の影"

[[discs.tracks]]
title = "everlasting force"

[[discs.tracks]]
title = "ever forever - ちーかま Style -"

[[discs.tracks]]
title = "悠久のむてき!"

[[discs.tracks]]
title = "おぷしょん!"

[[discs.tracks]]
title = "悠久のすてーじくりあ"

[[discs.tracks]]
title = "悠久のげーむおーばー"

[[discs.tracks]]
title = "Music teacher"
artist = "天門"

[[discs.tracks]]
title = "The real intention"
artist = "天門"

[[discs.tracks]]
title = "Positive cousin"
artist = "天門"
