[album]
title = "「アイドルマスター スターリットシーズン」オリジナルサウンドトラック"
artist = "堀畑智裕"
date = 2021-10-14
type = "absolute"
catalog = "TK-01"
tags = ["THE IDOLM@STER STARLIT SEASON"]

[[discs]]
catalog = "TK-01"

[[discs.tracks]]
title = "遥かなる世界へ"

[[discs.tracks]]
title = "ホーム ～みんなと一緒？～"

[[discs.tracks]]
title = "街へ行こう？"

[[discs.tracks]]
title = "UP&Down"

[[discs.tracks]]
title = "素敵なドレスオーダー"

[[discs.tracks]]
title = "BAR TIME"

[[discs.tracks]]
title = "ヒーリングタイム"

[[discs.tracks]]
title = "華麗なるアピールスクール"

[[discs.tracks]]
title = "レッスン？スタート？"

[[discs.tracks]]
title = "お仕事承りました？"

[[discs.tracks]]
title = "ボーカル☆レッスン"

[[discs.tracks]]
title = "ビジュアル☆レッスン"

[[discs.tracks]]
title = "ハッピーホリデイ ～次はどこかな？～"

[[discs.tracks]]
title = "S4Uのテーマ"

[[discs.tracks]]
title = "おはよう☆モーニング"

[[discs.tracks]]
title = "今日の終りに"

[[discs.tracks]]
title = "週の終りに"

[[discs.tracks]]
title = "穏やかな日々"

[[discs.tracks]]
title = "みんながいれば？やすらぎタイム"

[[discs.tracks]]
title = "嬉しい気持ち"

[[discs.tracks]]
title = "Producer Hearts"

[[discs.tracks]]
title = "グッド？ナイト"

[[discs.tracks]]
title = "ドタバタ☆パタパタ"

[[discs.tracks]]
title = "秘めた想い"

[[discs.tracks]]
title = "ソリチュード"

[[discs.tracks]]
title = "強い気持ち"

[[discs.tracks]]
title = "いっくよー？"

[[discs.tracks]]
title = "ありがとう！"

[[discs.tracks]]
title = "すれ違う想い"

[[discs.tracks]]
title = "はぁ……のテーマ"

[[discs.tracks]]
title = "宣戦布告！"

[[discs.tracks]]
title = "選択肢タイム！"

[[discs.tracks]]
title = "今日も元気にコミュニケーション？"

[[discs.tracks]]
title = "STELLA STAGE Main BGM (Bonus Track)"

[[discs.tracks]]
title = "GR@TITUDE TEASER PV Ver. (Bonus Track)"
