[album]
album_id = "e6702525-73c9-4738-aae6-274088dd09bd"
title = "t7s オリジナルサウンドトラック 2.0「-The Things She Left-」"
catalog = "VICL-65268"
artist = "岡ナオキ"
date = 2019-12-04
type = "absolute"
tags = ["Tokyo 7th シスターズ"]

[[discs]]
catalog = "VICL-65268"

[[discs.tracks]]
title = "怨の念"

[[discs.tracks]]
title = "仇なす者"

[[discs.tracks]]
title = "紅い宴～享～"

[[discs.tracks]]
title = "紅い宴～楽～"

[[discs.tracks]]
title = "人形たちの嘲笑み"

[[discs.tracks]]
title = "嵐の窓辺"

[[discs.tracks]]
title = "隔たる雲"

[[discs.tracks]]
title = "切れない鎖"

[[discs.tracks]]
title = "叶わなかった願い"

[[discs.tracks]]
title = "怨念狂躁曲"

[[discs.tracks]]
title = "敗者たちの雨"

[[discs.tracks]]
title = "愛と呼ぶ"

[[discs.tracks]]
title = "ハルカゼ -アイの調べ-"

[[discs.tracks]]
title = "虹を駆ける"

[[discs.tracks]]
title = "たったひとりの戰い"

[[discs.tracks]]
title = "青空まで歩いてきた"

[[discs.tracks]]
title = "すべての人の戰い"

[[discs.tracks]]
title = "初夏の手紙"

[[discs.tracks]]
title = "夏影"
