[album]
album_id = "fc732337-acab-4f78-99a5-a4720ee1607e"
title = "Across the Rainbow"
artist = "777☆SISTERS（春日部ハル（篠田みなみ）、天堂寺ムスビ（高田憂希）、角森ロナ（加隈亜衣）、野ノ原ヒメ（中島唯）、芹沢モモカ（井澤詩織）、臼田スミレ（清水彩香）、神城スイ（道井悠）、久遠寺シズカ（今井麻夏）、アレサンドラ・スース（大西沙織）、晴海サワラ（中村桜）、晴海カジカ（高井舞香）、晴海シンジュ（桑原由気））"
date = 2020-11-25
type = "normal"
catalog = "VIZL-1822"
tags = ["777☆SISTERS"]

[[discs]]
catalog = "VIZL-1822"

[[discs.tracks]]
title = "Across the Rainbow"

[[discs.tracks]]
title = "リボン"

[[discs.tracks]]
title = "Departures -あしたの歌-"

[[discs.tracks]]
title = "Across the Rainbow -OFF VOCAL-"
type = "instrumental"

[[discs.tracks]]
title = "リボン -OFF VOCAL-"
type = "instrumental"

[[discs.tracks]]
title = "Departures -あしたの歌- -OFF VOCAL-"
type = "instrumental"
