[album]
album_id = "c93f9bf6-7639-4917-a20c-c87953734419"
title = "The Present “4U”"
artist = "4U"
date = 2017-11-29
type = "normal"
catalog = "VIZL-1284"
tags = ["4U"]

[[discs]]
catalog = "VIZL-1284"

[[discs.tracks]]
title = "メロディーフラッグ"

[[discs.tracks]]
title = "Crazy Girl's Beat"

[[discs.tracks]]
title = "ROCKな☆アタシ"

[[discs.tracks]]
title = "青空Emotion"

[[discs.tracks]]
title = "パフェ・デ・ラブソング"

[[discs.tracks]]
title = "プレゼント・フォー・ユー"

[[discs.tracks]]
title = "カリフォルニア・ガールズ"
type = "drama"
