[album]
album_id = "a01b03e6-2721-4725-ae7a-d87b1cabb9c2"
title = "TRIGGER／Fire and Rose"
artist = "The QUEEN of PURPLE（越前ムラサキ（野村麻衣子）、瀬戸ファーブ（広瀬ゆうき）、屋ユメノ（山本彩乃）、三森マツリ（巽悠衣子））"
date = 2016-10-26
type = "normal"
catalog = "VIZL-1064"
tags = ["The QUEEN of PURPLE"]

[[discs]]
catalog = "VIZL-1064"

[[discs.tracks]]
title = "TRIGGER"

[[discs.tracks]]
title = "Fire and Rose"

[[discs.tracks]]
title = "TRIGGER -OFF VOCAL-"
type = "instrumental"

[[discs.tracks]]
title = "Fire and Rose -OFF VOCAL-"
type = "instrumental"

[[discs.tracks]]
title = "女王たちの午後"
type = "drama"
