[album]
title = "TAILWIND"
artist = "TrySail（麻倉もも、雨宮天、夏川椎菜）"
date = 2017-08-23
type = "normal"
catalog = "VVCL-1083"

[[discs]]
catalog = "VVCL-1083"

[[discs.tracks]]
title = "TAILWIND"

[[discs.tracks]]
title = "adrenaline!!!"

[[discs.tracks]]
title = "Chip log"

[[discs.tracks]]
title = "BraveSail"

[[discs.tracks]]
title = "バン!バン!!バンザイ!!!"

[[discs.tracks]]
title = "High Free Spirits"

[[discs.tracks]]
title = "センパイ。"

[[discs.tracks]]
title = "僕らのシンフォニー"

[[discs.tracks]]
title = "オリジナル。"

[[discs.tracks]]
title = "disco"

[[discs.tracks]]
title = "かかわり"

[[discs.tracks]]
title = "Journey"
