[album]
album_id = "54167f79-e867-41f5-802d-e17c1dd1b13d"
title = "ANIMA"
artist = "ReoNa"
date = 2020-07-22
type = "normal"
catalog = "VVCL-1680"
tags = ["ReoNa"]

[[discs]]
catalog = "VVCL-1680"

[[discs.tracks]]
title = "ANIMA"

[[discs.tracks]]
title = "雨に唄えば"

[[discs.tracks]]
title = "ミミック"

[[discs.tracks]]
title = "ANIMA -Instrumental-"
type = "instrumental"
