[album]
album_id = "48b6904f-7c76-47e7-9cb1-42df67cfee6d"
title = "Null"
artist = "ReoNa"
date = 2019-08-28
type = "normal"
catalog = "VVCL-1485"
tags = ["ReoNa"]

[[discs]]
catalog = "VVCL-1485"

[[discs.tracks]]
title = "怪物の詩"

[[discs.tracks]]
title = "Lotus"

[[discs.tracks]]
title = "決意の朝に"
