[album]
album_id = "9f777752-b9b2-4e68-8ae3-8ce3dd0ff94f"
title = "glory days"
edition = "期間生産限定盤"
artist = "春奈るな"
date = 2019-12-03
type = "normal"
catalog = "VVCL-1533"
tags = ["春奈るな", "冴えない彼女の育てかた Fine"]

[[discs]]
catalog = "VVCL-1533"

[[discs.tracks]]
title = "glory days"

[[discs.tracks]]
title = "君色シグナル"

[[discs.tracks]]
title = "ステラブリーズ"

[[discs.tracks]]
title = "カラフル。"

[[discs.tracks]]
title = "桜色ダイアリー"

[[discs.tracks]]
title = "glory days -Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "カラフル。-Instrumental-"
type = "instrumental"

[[discs.tracks]]
title = "桜色ダイアリー -Instrumental-"
type = "instrumental"
