[album]
title = "ステラブリーズ"
edition = "期間生産限定盤"
artist = "春奈るな"
date = 2017-05-03
type = "normal"
catalog = "VVCL-1017"
tags = ["春奈るな", "冴えない彼女の育てかた♭"]

[[discs]]
catalog = "VVCL-1017"

[[discs.tracks]]
title = "ステラブリーズ"

[[discs.tracks]]
title = "恋するポンパドール"

[[discs.tracks]]
title = "アイコトバ"

[[discs.tracks]]
title = "ステラブリーズ (TV Size)"
