[album]
album_id = "7fd86cd5-117b-4dce-a5b6-609af5cca6fa"
title = "SWEET HURT"
artist = "ReoNa"
date = 2018-09-29
type = "normal"
catalog = "VVCL-1285"
tags = ["ReoNa"]

[[discs]]
catalog = "VVCL-1285"

[[discs.tracks]]
title = "SWEET HURT"

[[discs.tracks]]
title = "おやすみの詩"

[[discs.tracks]]
title = "カナリア"

[[discs.tracks]]
title = "SWEET HURT -Instrumental-"
type = "instrumental"
