[category]
name = "少女☆歌劇 レヴュースタァライト"
type = "AAAA"
albums = [
  # プロローグ -Star Divine-
  "PCCG-01633",
  # プリンシパル -Fancy You-
  "BRCG-00053",
  # スタァライトシアター
  "PCCG-01641",
  # 星のダイアローグ
  "PCCG-70432",
  # Fly Me to the Star
  "PCCG-01703",
  # 99 ILLUSION！
  "BRMM-10151",
  # ラ レヴュー ド マチネ
  "PCCG-01706",
  # ラ レヴュー ド ソワレ
  "PCCG-01707",
  # 少女☆歌劇 レヴュースタァライト オリジナルサウンドトラック
  "PCCG-01716",
  # 約束タワー
  "PCCG-70445",
  # プラチナ・フォルテ
  "PCCG-01760",
  # 百色リメイン【華恋＆ひかり＆まひるver.】
  "BRMM-10186",
  # 百色リメイン【真矢＆クロディーヌver.】
  "BRMM-10187",
  # 百色リメイン【純那＆ななver.】
  "BRMM-10188",
  # 百色リメイン【双葉＆香子ver.】
  "BRMM-10189",
  # 蝶になってみませんか
  "PCCG-01780",
  # ショウタイム フロンティア！
  "PCCG-01785",
  # ラ レヴュー・オン・ボワット
  "BRCG-00066",
  # Star Diamond
  "PCCG-01788",
  # ラ・レヴュー・エターナル
  "PCCG-01810",
  # Star Parade
  "PCCG-01863",
  # 再生讃美曲
  "PCCG-01914",
  # BLUE ANTHEM
  "BRMM-10338",
  # 少女☆歌劇 レヴュースタァライト ベストアルバム
  "PCCG-01983",
  # イニシャル
  "MORA-A90098",
  # 不死鳥のフランメ
  "MORA-A96568",
  # My friend ~Arrie~
  "TGCS-10947",
  # You are a ghost, I am a ghost 〜劇場のゴースト〜
  "TGCS-10948",
  # 恋は太陽 ~CIRCUS!~
  "TGCS-10949",
  # 素敵なドレスを着させてよ
  "TGCS-11869",
  # 「Polestar」華恋・ひかり 歌い分けver.CD
  "DSP-02288",
  # 「Polestar」華恋・まひる 歌い分けver.CD
  "DSP-02289",
  # 「Polestar」真矢・クロディーヌ 歌い分けver.CD
  "DSP-02290",
  # 「Polestar」純那・なな 歌い分けver.CD
  "DSP-02291",
  # 「Polestar」双葉・香子 歌い分けver.CD
  "DSP-02292",
  # 少女☆歌劇 レヴュースタァライト -The LIVE- #1 revival 特典CD
  "BRMM-10109",
  # 少女☆歌劇 レヴュースタァライト -The LIVE- #2 Transition 特典CD
  "BRMM-10175",
  # 少女☆歌劇 レヴュースタァライト-The LIVE-#2 revival 特典CD
  "BRMM-10213",
  # 少女☆歌劇 レヴュースタァライト オーケストラライブ "Starry Konzert" Live CD
  "DSP-02209",
  # 少女☆歌劇 レヴュースタァライト 1stスタァライブ "Starry Sky" Live CD
  "DSP-02186",
  # 少女☆歌劇 レヴュースタァライト 2ndスタァライブ "Starry Desert" Live CD
  "DSP-02197",
  # 少女☆歌劇 レヴュースタァライト 3rdスタァライブ "Starry Diamond" Live CD
  "DSP-02243~4",
  # 少女☆寸劇 オールスタァライト オリジナルサウンドトラック
  "TGCS-11531",
  # 私たちはもう舞台の上
  "PCCG-02035",
  # 劇場版 少女☆歌劇 レヴュースタァライト 劇中歌アルバムVol.1
  "PCCG-02036",
  # 劇場版 少女☆歌劇 レヴュースタァライト 劇中歌アルバムVol.2
  "PCCG-02037",
  # サイカイ合図【花ver.】
  "BRMM-10415",
  # サイカイ合図【星ver.】
  "BRMM-10416",
]
