[category]
name = "THE IDOLM@STER MILLION LIVE"
type = "AAAA"
albums = []

[[subcategory]]
name = "THE IDOLM@STER MILLION LIVE SPECIAL ALBUMS"
albums = [
  # THE IDOLM@STER LIVE THE@TER SELECTION
  "BNGI-00007",
  # THE IDOLM@STER MILLION LIVE! 1stLIVE HAPPY☆PERFORM@NCE!! Blu-ray "COMPLETE THE@TER" CD
  "LAPC-1073",
  # THE IDOLM@STER MILLION LIVE! 765プロライブシアター記念パーティードラマCD
  "BNGI-00002",
  # THE IDOLM@STER 765PRO LIVE THE@TER COLLECTION Vol.1
  "LACA-9398~9",
  # THE IDOLM@STER MILLION LIVE! 2ndLIVE ENJOY H@RMONY!! LIVE Blu-ray "COMPLETE THE@TER" CD
  "LAPC-1074",
  # THE IDOLM@STER MILLION LIVE! 765プロライブシアター 3周年記念イベントリポート ドラマCD
  "BNEI-00003",
  # THE IDOLM@STER MILLION LIVE! 4th ANNIVERSARY 五十一人一首 朗読CD
  "BNEI-ML／RI-2017",
  # 君との明日を願うから
  "LZC-1132",
  # THE IDOLM@STER 765 MILLIONSTARS HOTCHPOTCH FESTIV@L!! LIVE CD
  "LAPP-1107",
  # THE IDOLM@STER MILLION LIVE! 5thLIVE BRAND NEW PERFORM@NCE!!! LIVE CD
  "LAPP-1109",
  # THE IDOLM@STER MILLION LIVE! 6thLIVE TOUR UNI-ON@IR!!!! オリジナルLIVE音源 CD
  "LAPP-1120",
  # なんどでも笑おう【ミリオンライブ！盤】
  "LACM-24025",
  # THE IDOLM@STER MILLION LIVE! ZWEIGLANZ アライアンス・スターダスト
  "LACM-24004",
  # THE IDOLM@STER MILLION LIVE! STAR EQUINOX
  "LACM-24088",
  # リフレインキス (Brand New Ver.)
  "LZC-1901",
  # 花びらメモリーズ
  "LZC-1902",
  # VOY@GER【ミリオンライブ！盤】
  "LACM-24163",
  # THE IDOLM@STER MILLION LIVE! 聖ミリオン女学園
  "LACM-24159",
  # DIAMOND JOKER
  "LZC-1938",
  # 真夏のダイヤ☆
  "LZC-1939",
  # シークレットジュエル ～魅惑の金剛石～
  "LZC-1940",
  # ダイヤモンド・クラリティ
  "LZC-1941",
]
