[category]
name = "プロジェクトセカイ カラフルステージ！"
type = "AAAA"
albums = []

[[subcategory]]
name = "Leo/need"
albums = [
  # needLe／ステラ
  "BRMM-10402"
]

[[subcategory]]
name = "MORE MORE JUMP！"
albums = [
  # アイドル新鋭隊／モア！ジャンプ！モア！
  "BRMM-10403"
]

[[subcategory]]
name = "Vivid BAD SQUAD"
albums = [
  # Ready Steady／Forward
  "BRMM-10404"
]

[[subcategory]]
name = "ワンダーランズ×ショウタイム"
albums = [
  # セカイはまだ始まってすらいない／potatoになっていく
  "BRMM-10405"
]

[[subcategory]]
name = "25時、ナイトコードで。"
albums = [
  # 悔やむと書いてミライ／携帯恋話／ジャックポットサッドガール
  "BRMM-10406"
]
